// Viewing fields and filtering never mutate copies, acquisitions or allocations.
const rosterFields={name:'Card',type:'Card type',subtype:'Subtype',mechanic:'Mechanic',color:'Color',mana:'Mana cost',mv:'Mana value',price:'Cost · USD',source:'Source',placement:'Status',deck:'Deck / list',bench:'Bench',offer:'Sell / Trade',quantity:'Quantity'};
const rosterDefaultColumns=['name','type','source','placement','deck'];
let rosterColumns=[...rosterDefaultColumns],rosterFacets={type:'all',subtype:'all',mechanic:'all',color:'all',deck:'all',bench:'all',min:'',max:'',mv:'all'};
function clearRosterFilters(){rosterFacets={type:'all',subtype:'all',mechanic:'all',color:'all',deck:'all',bench:'all',min:'',max:'',mv:'all'};const state=tableState.roster;Object.assign(state,{search:'',source:'all',placement:'all',offer:false,group:'none'});q('#v-roster').innerHTML='';}
function rosterRecord(r){const m=rosterMetadata[r.name]||{},g=r.draft?groups.find(g=>g.id===r.groupId):null;return {...r,type:m.type||'Unknown',subtype:m.subtype||'None',mechanic:m.mechanic||'Unclassified',color:m.color||'Unknown',mana:m.mana||'—',mv:m.mv??null,price:m.price??null,deck:r.deck||(g?.commander?g.name:''),bench:r.source==='Owned'&&/bench/i.test(r.location)?'Yes':'No',offer:r.sellTrade?'Yes':'No',quantity:r.quantity||1};}
function rosterItems(){let list=[...rows,...allDraftEntries()];if(activeGroup!=='all'){const g=groups.find(g=>g.id===activeGroup);list=list.filter(r=>g?.deck?r.deck===g.deck:(g?.refs||[]).includes(r.id)||r.groupId===g?.id);}const s=tableState.roster,f=rosterFacets;return list.map(rosterRecord).filter(r=>(s.source==='all'||r.source===s.source)&&(s.placement==='all'||r.placement===s.placement)&&(!s.offer||r.sellTrade)&&Object.entries(f).every(([k,v])=>v==='all'||v===''||(k==='min'?r.price!==null&&r.price>=Number(v):k==='max'?r.price!==null&&r.price<=Number(v):k==='mv'?r.mv!==null&&String(r.mv)===v:['type','subtype','mechanic','color'].includes(k)?String(r[k]).split(' · ').includes(v):String(r[k])===v))&&Object.values(r).join(' ').toLowerCase().includes(s.search.toLowerCase())).sort((a,b)=>(['price','mv','quantity'].includes(s.sort)?(a[s.sort]??Infinity)-(b[s.sort]??Infinity):String(a[s.sort]??'').localeCompare(String(b[s.sort]??'')))*s.direction);}
function renderTable(key){if(key!=='roster')return renderBaseTable(key);const host=q('#v-roster'),state=tableState.roster;const facet=(key,label,values)=>`<label class="v-field">${label}<select class="v-select" data-roster-facet="${key}"><option value="all">Any</option>${values.map(v=>`<option>${esc(v)}</option>`).join('')}</select></label>`;
if(!host.querySelector('table')){
 const values=key=>[...new Set(Object.values(rosterMetadata).flatMap(m=>String(m[key]??'Unknown').split(' · ')))].sort();
 host.innerHTML=`<div class="v-table-tools"><label class="v-table-search">Search cards<input type="search" data-table-search="roster" placeholder="Name, type, mechanic or deck"></label><button class="v-button" type="button" data-filter-toggle aria-expanded="false" aria-controls="v-roster-filters">Filters</button><button class="v-button" type="button" data-column-toggle aria-expanded="false" aria-controls="v-roster-columns">Columns</button><label class="v-table-group">Group by<select class="v-select" data-table-group>${['none','type','source','placement','deck','color'].map(k=>`<option value="${k}">${k==='none'?'No grouping':rosterFields[k]}</option>`).join('')}</select></label></div>
 <div id="v-roster-filters" class="v-filter-panel" hidden>${facet('type','Card type',values('type'))}${facet('subtype','Subtype',values('subtype'))}${facet('mechanic','Mechanic',values('mechanic'))}${facet('color','Color',values('color'))}${facet('mv','Mana value',values('mv').filter(v=>v!=='Unknown'))}<label class="v-field">Source<select class="v-select" data-filter-field="source"><option value="all">Any</option><option>Owned</option><option>Ordered</option><option>To buy</option><option>Plan only</option></select></label><label class="v-field">Status / placement<select class="v-select" data-filter-field="placement"><option value="all">Any</option><option>In deck</option><option>Reserved</option><option>Bench</option><option>Draft</option></select></label>${facet('deck','Deck / list',[])}${facet('bench','Physically on bench',['Yes','No'])}<label class="v-field">Minimum cost · USD<input type="number" min="0" step="0.01" data-roster-facet="min"></label><label class="v-field">Maximum cost · USD<input type="number" min="0" step="0.01" data-roster-facet="max"></label><label class="v-g-toggle"><input type="checkbox" data-filter-offer>Sell / Trade only</label><div class="v-filter-foot"><button type="button" class="v-button" data-clear-filters>Clear filters</button><span class="v-small">Cost uses the catalog snapshot; unknown costs never count as zero.</span></div></div>
 <div id="v-roster-columns" class="v-columns-panel" hidden><p class="v-small">Choose what matters to you. Card and Actions stay visible.</p><div class="v-column-options">${Object.entries(rosterFields).map(([k,label])=>`<label><input type="checkbox" data-column="${k}" ${rosterColumns.includes(k)?'checked':''} ${k==='name'?'disabled':''}>${label}</label>`).join('')}</div><button type="button" class="v-button" data-reset-columns>Reset columns</button></div><div class="v-filter-summary" aria-live="polite"></div><div class="v-roster-scroll"><table class="v-data-table"><caption>Card roster. Use column headers to sort; filters and columns are above.</caption><colgroup></colgroup><thead></thead><tbody></tbody></table></div>`;
 host.querySelector('[data-table-search]').oninput=e=>{state.search=e.target.value;renderTable(key);};host.querySelector('[data-table-group]').onchange=e=>{state.group=e.target.value;renderTable(key);};
 for(const [attr,id] of [['data-filter-toggle','v-roster-filters'],['data-column-toggle','v-roster-columns']])host.querySelector('['+attr+']').onclick=e=>{const p=q('#'+id);p.hidden=!p.hidden;e.currentTarget.setAttribute('aria-expanded',String(!p.hidden));};
 host.querySelectorAll('[data-roster-facet]').forEach(e=>e.onchange=()=>{rosterFacets[e.dataset.rosterFacet]=e.value;renderTable(key);});
 host.querySelectorAll('[data-filter-field]').forEach(e=>e.onchange=()=>{state[e.dataset.filterField]=e.value;renderTable(key);});
 host.querySelector('[data-filter-offer]').onchange=e=>{state.offer=e.target.checked;renderTable(key);};host.querySelector('[data-clear-filters]').onclick=()=>{activeGroup='all';clearRosterFilters();syncGroups();renderRoster();};
 host.querySelectorAll('[data-column]').forEach(e=>e.onchange=()=>{rosterColumns=Object.keys(rosterFields).filter(k=>k==='name'||host.querySelector(`[data-column="${k}"]`).checked);if(!rosterColumns.includes(state.sort)){state.sort='name';state.direction=1;}renderTable(key);});host.querySelector('[data-reset-columns]').onclick=()=>{rosterColumns=[...rosterDefaultColumns];host.querySelectorAll('[data-column]').forEach(e=>e.checked=rosterColumns.includes(e.dataset.column));state.sort='name';state.direction=1;renderTable(key);};
}
host.querySelector('[data-table-search]').value=state.search;host.querySelector('[data-table-group]').value=state.group;host.querySelector('[data-filter-offer]').checked=state.offer;
const decks=[...new Set([...rows,...allDraftEntries()].map(rosterRecord).map(r=>r.deck).filter(Boolean))].sort();host.querySelector('[data-roster-facet=deck]').innerHTML='<option value="all">Any</option>'+decks.map(d=>`<option>${esc(d)}</option>`).join('');
host.querySelectorAll('[data-roster-facet]').forEach(e=>e.value=rosterFacets[e.dataset.rosterFacet]);host.querySelectorAll('[data-filter-field]').forEach(e=>e.value=state[e.dataset.filterField]);
const columns=[...rosterColumns,'actions'],visible=rosterItems(),widths={name:230,type:130,subtype:140,mechanic:150,color:130,mana:110,mv:100,price:110,source:110,placement:120,deck:150,bench:80,offer:100,quantity:90,actions:64};host.querySelector('table').style.minWidth=columns.reduce((n,k)=>n+widths[k],0)+'px';
host.querySelector('colgroup').innerHTML=columns.map(k=>`<col style="width:${widths[k]}px">`).join('');host.querySelector('thead').innerHTML='<tr>'+columns.map(k=>`<th scope="col" ${k!=='actions'?`data-sort-column="${k}" aria-sort="${state.sort===k?(state.direction===1?'ascending':'descending'):'none'}"`:''}>${k==='actions'?'Actions':`<button class="v-sort-head" type="button" data-sort="${k}">${rosterFields[k]}<span aria-hidden="true">${state.sort===k?(state.direction===1?'↑':'↓'):'↕'}</span></button>`}</th>`).join('')+'</tr>';
const cell=(r,k)=>k==='actions'?rowMenu(r,key):k==='name'?`<span class="v-card-label">${esc(r.name)}</span><span class="v-cell-note">${r.quantity} ${r.draft?'planned':r.source==='To buy'?'copy needed':'copy'} · ${esc(r.purpose)}</span>${r.sellTrade?'<span class="v-cell-note v-offer-label">Sell / Trade</span>':''}`:k==='source'?`<span class="v-source-label">${esc(r.source)}</span>`:k==='placement'?`<span class="v-placement-label">${esc(r.placement)}</span>${r.deck&&locks[r.deck]?'<span class="v-cell-note">Locked</span>':''}`:k==='price'?(r.price===null?'Unknown':'$'+r.price.toFixed(2)):esc(r[k]??'Unknown');
const grouped=state.group==='none'?[['',visible]]:[...Map.groupBy(visible,r=>r[state.group]||'Unassigned')].sort(([a],[b])=>a.localeCompare(b));host.querySelector('tbody').innerHTML=grouped.map(([name,list])=>(name?`<tr class="v-group-row"><th scope="rowgroup" colspan="${columns.length}">${esc(name)} · ${list.length} rows</th></tr>`:'')+list.map(r=>`<tr data-record="${esc(r.id)}">${columns.map(k=>`<td data-cell="${k}">${cell(r,k)}</td>`).join('')}</tr>`).join('')).join('')||`<tr><td colspan="${columns.length}">No matching cards. Adjust or clear filters.</td></tr>`;
const active=[...Object.entries(rosterFacets).filter(([k,v])=>v!==''&&v!=='all'),...['source','placement'].filter(k=>state[k]!=='all').map(k=>[k,state[k]]),...(state.offer?[['offer','Sell / Trade']]:[])];host.querySelector('[data-filter-toggle]').textContent='Filters'+(active.length?' · '+active.length:'');host.querySelector('.v-filter-summary').innerHTML=`<span>${visible.length} rows · ${visible.reduce((n,r)=>n+r.quantity,0)} cards</span>`+active.map(([k,v])=>`<button type="button" data-remove-filter="${k}">${esc((rosterFields[k]||k)+': '+v)} ×</button>`).join('');host.querySelectorAll('[data-remove-filter]').forEach(b=>b.onclick=()=>{const k=b.dataset.removeFilter;if(k==='offer')state.offer=false;else if(k in rosterFacets)rosterFacets[k]=['min','max'].includes(k)?'':'all';else state[k]='all';renderTable(key);});
host.querySelectorAll('[data-sort]').forEach(b=>b.onclick=()=>{const k=b.dataset.sort;state.direction=state.sort===k?-state.direction:1;state.sort=k;renderTable(key);});bindMenus(host,key);
// Menus escape the horizontal table scroller without moving any table cells.
host.querySelectorAll('.v-row-menu').forEach(d=>{const menu=d.querySelector('.v-menu-options');menu.setAttribute('popover','manual');d.addEventListener('toggle',()=>{if(!d.open){if(menu.matches(':popover-open'))menu.hidePopover();return;}menu.showPopover();const b=d.getBoundingClientRect(),m=menu.getBoundingClientRect();menu.style.left=Math.max(12,Math.min(b.right-m.width,innerWidth-m.width-12))+'px';menu.style.top=Math.max(12,b.bottom+m.height+8<innerHeight?b.bottom+5:b.top-m.height-5)+'px';});});
}
