# Copyright (c) 2026 Rob Minor. All rights reserved. See LICENSE.
"""Train B B4: semantic faults, one at a time; run only while no other engine suite is running."""
SUITES = [
    'tests/engine-attack-requirements.mjs',
    'tests/engine-defender-permission.mjs',
    'tests/engine-ability-haste.mjs',
    'tests/engine-unless-return.mjs',
    'tests/engine-sacrificed-amounts.mjs',
    'tests/engine-top-card-abilities.mjs',
]
BREAKS = [
    ('attack requirement credit removed', 'game/tools/engine-constructs.mjs',
     '  MustAttack: "rules/combat",', ''),
    ('defender permission credit removed', 'game/tools/engine-constructs.mjs',
     '  CanAttackDefender: "rules/statics",', ''),
    ('ability haste credit removed', 'game/tools/engine-constructs.mjs',
     '  ActivateAbilityAsIfHaste: "keywords/timing",', ''),
    ('attack requirements omitted', 'game/engine/rules/combat.mjs',
     'const requires = requiresOf(state, options);', 'const requires = [];'),
    ('attack cost forces payment', 'game/engine/rules/combat.mjs',
     'const ways = options.filter((o) => o.cardId === id && free(o));', 'const ways = options.filter((o) => o.cardId === id);'),
    ('planeswalker matching overcounts attackers', 'game/engine/rules/combat.mjs',
     'return {each, tight, caps, most: placesFilled(tight, caps)};', 'return {each, tight, caps, most: tight.length};'),
    ('overlapping attack requirements treated equally', 'game/engine/rules/combat.mjs',
     'for (const weight of weights.slice(0, -1)) {', 'for (const weight of []) {'),
    ('requirement tiers omit tied attackers', 'game/engine/rules/combat.mjs',
     'const tier = tight.filter((r) => r.sources.length >= weight);',
     'const tier = tight.filter((r) => r.sources.length >= weight).slice(0, 1);'),
    ('engine accepts missing required attacker', 'game/engine/rules/combat.mjs',
     'if (new Set(picked.map((o) => o.cardId).filter((id) => need.values.includes(id))).size < need.least) throw new Error(need.why);',
     'if (false) throw new Error(need.why);'),
    ('controller accepts missing required attacker', 'game/engine/controller.mjs',
     'if (met.size < (need.least ?? 0)) throw new Error(need.why ?? "Invalid selection");',
     'if (false) throw new Error(need.why ?? "Invalid selection");'),
    ('attack requirement ignores condition', 'game/engine/rules/statics.mjs',
     'if (conditionHolds(state, ability.condition, context) && matchesSelector(chosenFor(ability, holder).affects, state, id, context)) sources.push(holderId);',
     'if (matchesSelector(chosenFor(ability, holder).affects, state, id, context)) sources.push(holderId);'),
    ('pilot omits required additions', 'game/engine/pilots/house-pilot.mjs',
     'if (n >= requirements.length) return selected;', 'if (true) return selected;'),
    ('pilot keeps optional attack blocking requirement', 'game/engine/pilots/house-pilot.mjs',
     'if (preserved !== null) return preserved;', 'return preserved ?? [...indices];'),
    ('pilot never backtracks across requirement groups', 'game/engine/pilots/house-pilot.mjs',
     'if (left <= 0) return solve(n + 1, list);', 'if (left <= 0) return list;'),
    ('pilot drops nonconflicting optional attacks on retry', 'game/engine/pilots/house-pilot.mjs',
     'for (const index of indices) {\n    const option = options[index];',
     'for (const index of []) {\n    const option = options[index];'),
    ('defender permission lost', 'game/engine/rules/statics.mjs',
     'if (ability.against === undefined) return true;', 'if (ability.against === undefined) return false;'),
    ('defender allowed at planeswalkers', 'game/engine/rules/statics.mjs',
     'if (ability.against !== "attackedYouLastTurn" || planeswalker !== null) continue;',
     'if (ability.against !== "attackedYouLastTurn") continue;'),
    ('defender accepts any past attack', 'game/engine/rules/statics.mjs',
     '(state.players[player]?.attackedPlayers ?? []).includes(you)', '(state.players[player]?.attackedPlayers ?? []).length > 0'),
    ('defender condition bypassed', 'game/engine/rules/statics.mjs',
     'if (!conditionHolds(state, ability.condition, context) || !matchesSelector(chosenFor(ability, holder).affects, state, id, context)) continue;',
     'if (!matchesSelector(chosenFor(ability, holder).affects, state, id, context)) continue;'),
    ('planeswalker attack counted as player attack', 'game/engine/rules/combat.mjs',
     'if (attack.planeswalker === undefined && !attackedPlayers.includes(attack.defender)) attackedPlayers.push(attack.defender);',
     'if (!attackedPlayers.includes(attack.defender)) attackedPlayers.push(attack.defender);'),
    ('attack history never resets', 'game/engine/rules/turn.mjs',
     'if (state.players[state.activePlayer].attackedPlayers) state.players[state.activePlayer].attackedPlayers = [];', ''),
    ('ability haste permission ignored', 'game/engine/keywords/timing.mjs',
     'return summoningSick(state, id) && !ruleChanged(state, "activate-as-though-haste", id);', 'return summoningSick(state, id);'),
    ('ability haste ignores opponents', 'game/engine/keywords/timing.mjs',
     'return summoningSick(state, id) && !ruleChanged(state, "activate-as-though-haste", id);', 'return false;'),
    ('return cost omitted from resolution', 'game/engine/script/effects/asking.mjs',
     '...(params.returnToHand ? {returnToHand: structuredClone(params.returnToHand)} : {}),', ''),
    ('return cost accepts its own source', 'game/engine/script/effects/asking.mjs',
     'compileSelector({...awaiting.returnToHand, what: "permanent", controller: "you"})',
     'compileSelector({...awaiting.returnToHand, another: false, what: "permanent", controller: "you"})'),
    ('return payment never moves creature', 'game/engine/script/effects/asking.mjs',
     'moveOne(state, option.bounce, "hand", events);', 'void option.bounce;'),
    ('return schema permits mixed cost', 'game/engine/script/schema.mjs',
     'if (effect.sacrifice !== undefined || effect.discard !== undefined)', 'if (false)'),
    ('sacrifice omits last known information', 'game/engine/rules/actions.mjs',
     'if (was) (entry.sacrificed ??= []).push(was);', 'void was;'),
    ('stack drops sacrificed context', 'game/engine/rules/stack.mjs',
     '...(entry.sacrificed ? {sacrificed: entry.sacrificed} : {}),', ''),
    ('resolution drops sacrificed context', 'game/engine/script/resolution.mjs',
     '...(context.sacrificed ? {sacrificed: context.sacrificed} : {})', ''),
    ('sacrificed power and toughness swapped', 'game/engine/script/amount.mjs',
     'n = (value.powerOf === "sacrificed" ? was?.power : was?.toughness) ?? 0;',
     'n = (value.powerOf === "sacrificed" ? was?.toughness : was?.power) ?? 0;'),
    ('top card grants triggered abilities', 'game/engine/rules/layers.mjs',
     '(card.abilities ?? []).filter((a) => a.kind === "activated" || a.kind === "mana")', '(card.abilities ?? [])'),
    ('top card omits mana abilities', 'game/engine/rules/layers.mjs',
     '(card.abilities ?? []).filter((a) => a.kind === "activated" || a.kind === "mana")', '(card.abilities ?? []).filter((a) => a.kind === "activated")'),
    ('top card subtype condition ignored', 'game/engine/rules/layers.mjs',
     'if (!card || !wanted.every((t) => hasSubtype(card.subtypes ?? [], everyCreatureType(card.keywords), t))) return null;', 'if (!card) return null;'),
    ('top card abilities fast path bypasses grant', 'game/engine/rules/layers.mjs',
     'apply.addAbilities || apply.removeAllAbilities || apply.topCardAbilities', 'apply.addAbilities || apply.removeAllAbilities'),
]
