# Copyright (c) 2026 Rob Minor. All rights reserved. See LICENSE.
"""Train B3 memory faults. Run serially with breaks.py; every replacement remains valid JavaScript."""
SUITES = [f'tests/engine-{name}.mjs' for name in [
    'linked-memory', 'hidden-exile', 'moved-memory', 'copy-memory',
    'source-memory', 'card-choice-memory', 'enter-transformed', 'power-comparison',
]]
BREAKS = [
    ('hideaway credit', 'game/tools/engine-constructs.mjs', '  Hideaway: "dig",', ''),
    ('hidden move only intended destination', 'game/engine/script/effects/zones.mjs',
     'faceDown === true && to === "exile" && destination === "exile"',
     'faceDown === true && destination === "exile"'),
    ('redirected hidden move public event', 'game/engine/script/effects/zones.mjs',
     'if (faceDown === true && !asDown && !hidden) card = leavingRef(state, id);', ''),
    ('linked selector source isolation', 'game/engine/script/filter.mjs',
     'if (selector.exiledWith === "self" && !exiledWithSource(state, linkSource(context)).includes(id)) return false;',
     'if (false) return false;'),
    ('linked source after departure', 'game/engine/script/filter.mjs',
     'context?.source ?? context?.lastKnown?.cardId ?? null', 'context?.source ?? null'),
    ('dig records linked exile', 'game/engine/script/effects/asking.mjs',
     'links[awaiting.link] = [...(links[awaiting.link] ?? []), ...found.filter((id) => state.objects[id]?.zone === "exile")];',
     'links[awaiting.link] = [];'),
    ('hidden exile has no characteristics', 'game/engine/state/index.mjs',
     'return addObject(state, {...FACE_DOWN_EXILED, ...kept, faceDown: true, faceDownCard}, zone, player);',
     'return addObject(state, {...FACE_DOWN, ...kept, faceDown: true, faceDownCard}, zone, player);'),
    ('hidden exile name privacy', 'game/engine/projection.mjs',
     'faceDown && viewer !== null && object.faceDownCard?.card && mayLookAt(state, object, viewer, controller)',
     'faceDown && viewer !== null && object.faceDownCard?.card'),
    ('hideaway compiled hidden', 'game/engine/cards/index.mjs',
     'count: ability.amount ?? 1, take: 1, to: "exile", faceDown: true, link: true, rest: "bottom", random: true',
     'count: ability.amount ?? 1, take: 1, to: "exile", faceDown: false, link: true, rest: "bottom", random: true'),
    ('hideaway past controller permission', 'game/engine/state/index.mjs',
     'card.lookers = [...new Set([...(card.lookers ?? []), controller])];',
     'card.lookers = [...(card.lookers ?? [])];'),
    ('hideaway departing layered controller', 'game/engine/script/effects/zones.mjs',
     'if (leftBehind) rememberExileLooker(state, departed, leftBehind.controller);', ''),
    ('hideaway initial current controller', 'game/engine/script/effects/asking.mjs',
     'if (state.objects[awaiting.link]?.zone === "battlefield") rememberExileLooker(state, awaiting.link, controllerOf(state, awaiting.link));', ''),
    ('hideaway layered permission checkpoint', 'game/engine/rules/sba.mjs',
     'rememberExileLooker(state, source, controllerOf(state, source));', 'void source;'),
    ('moved remembers pre-move snapshot', 'game/engine/script/effects/zones.mjs',
     'context.movedWas = movedWas;', 'context.movedWas = [];'),
    ('moved condition fails without matching move', 'game/engine/script/condition.mjs',
     'if (!fits) return false;', 'if (false) return false;'),
    ('moved branch context propagation', 'game/engine/script/resolution.mjs',
     'movedWas: resolving.context.movedWas, searched: resolving.context.searched, lastKnown: resolving.context.lastKnown});',
     'movedWas: undefined, searched: resolving.context.searched, lastKnown: resolving.context.lastKnown});'),
    ('copy adds abilities', 'game/engine/script/effects/permanents.mjs',
     '...structuredClone(except.addAbilities ?? [])', '...[]'),
    ('copy binds remembered card', 'game/engine/script/effects/permanents.mjs',
     'effect.targets === "remembered" ? {targets: [...(remembered ?? [])]} : {}',
     'effect.targets === "remembered" ? {targets: []} : {}'),
    ('copy uses last known copiable values', 'game/engine/script/effects/permanents.mjs',
     'params.asItLastWas === true && context.about?.copiedAs && state.objects[id]',
     'false && context.about?.copiedAs && state.objects[id]'),
    ('copy snapshot forwarded through death trigger', 'game/engine/rules/trigger.mjs',
     'fields.from?.zoneType === "Battlefield" ? fields.leftBehind?.copiable : undefined', 'undefined'),
    ('self filters last known identity', 'game/engine/script/filter.mjs',
     'if (s.self === true && lki.cardId !== context.source) return false;', ''),
    ('remembered off-field printed figures', 'game/engine/script/amount.mjs',
     'ref === "remembered" && id !== null && state.objects[id] && state.objects[id].zone !== "battlefield"',
     'false && id !== null && state.objects[id] && state.objects[id].zone !== "battlefield"'),
    ('departed stack source captures LKI', 'game/engine/script/effects/zones.mjs',
     'entry.lastKnown = structuredClone(leftBehind);', 'entry.lastKnown = null;'),
    ('stack LKI is not overwritten', 'game/engine/script/effects/zones.mjs',
     'entry.cardId === departed && !entry.lastKnown', 'entry.cardId === departed'),
    ('choose among trigger cards', 'game/engine/script/effects/asking.mjs',
     'params.among === "those cards" ? context.about?.cards ?? [] : context.remembered ?? []',
     'params.among === "those cards" ? [] : context.remembered ?? []'),
    ('choose random without replacement', 'game/engine/script/effects/asking.mjs',
     'rng.pick(cards.filter((id) => !picked.includes(id)))', 'rng.pick(cards)'),
    ('exile choice cannot fail to find', 'game/engine/script/effects/asking.mjs',
     'const min = params.upTo || (!faceUp && hasQuality(params.selector)) ? 0 : Math.min(count, cards.length);',
     'const min = 0;'),
    ('searched outcome reaches resolution', 'game/engine/script/resolution.mjs',
     'if (!Array.isArray(outcome) && outcome.searched === true) state.resolving.context.searched = true;', ''),
    ('searched condition rejects absent search', 'game/engine/script/condition.mjs',
     'if (condition.searched === true && searched !== true) return false;', ''),
    ('transformed uses back face', 'game/engine/state/index.mjs',
     '(from.face === "back" || transformed === true)', '(from.face === "back")'),
    ('transformed rejects ordinary cards', 'game/engine/script/effects/zones.mjs',
     'if (backUp && !(object.mdfc?.transforming === true && PERMANENT_TYPES.some((type) => (object.mdfc.back.types ?? []).includes(type)))) return null;',
     'if (backUp && !object.mdfc) return null;'),
    ('transformed flicker forwards back face', 'game/engine/script/effects/zones.mjs',
     '...(params.returnWithCounter ? {withCounter: params.returnWithCounter} : {}), ...(params.transformed === true ? {transformed: true} : {})',
     '...(params.returnWithCounter ? {withCounter: params.returnWithCounter} : {})'),
    ('power comparison strictly less', 'game/engine/script/filter.mjs',
     'Number.isInteger(theirs) && power < theirs', 'Number.isInteger(theirs) && power <= theirs'),
    ('power comparison matching source LKI', 'game/engine/script/filter.mjs',
     '(source === null || source === undefined || context.lastKnown.cardId === source)', 'true'),
]
