# Copyright (c) 2026 Rob Minor. All rights reserved. See LICENSE.
"""Build the Engine Catalog page -- Rob's progress page, a private claude.ai artifact -- from game/docs/engine-catalog.json.

The page is catalog-page.html with the catalog's data in it and a line saying where it stands. Usage, from the
repository root of the branch at the top of the stack:

    python game/tools/batch/build-catalog-page.py <out.html> "Generated by game/tools/engine-catalog.mjs as of batch 69, pull request #557. ..."

Then publish <out.html> with the Artifact tool to the page's existing URL (Rob's: claude.ai/artifact/2p7KuxoPTNF1wvk2GAsH72,
read it first from a new session), so the link he has keeps working. Keep the output out of the repository: the page
is the artifact, not a served file.
"""
import json
import os
import sys

if len(sys.argv) != 3:
    sys.exit(__doc__)
out, source = sys.argv[1], sys.argv[2]
here = os.path.dirname(os.path.abspath(__file__))
with open(os.path.join(here, 'catalog-page.html'), encoding='utf-8') as f:
    page = f.read()
for placeholder in ('__CATALOG__', '__SOURCE__'):
    if page.count(placeholder) != 1:
        sys.exit(f'catalog-page.html names {placeholder} {page.count(placeholder)} times, not once')
with open(os.path.join(os.getcwd(), 'game', 'docs', 'engine-catalog.json'), encoding='utf-8') as f:
    data = json.load(f)
# The data goes in a JSON script element (no "</" may close it early); the line goes in a JS template literal.
payload = json.dumps(data, ensure_ascii=False, separators=(',', ':')).replace('</', '<\\/')
line = source.replace('\\', '\\\\').replace('`', '\\`').replace('${', '\\${')
page = page.replace('__CATALOG__', payload).replace('__SOURCE__', line)
with open(out, 'w', encoding='utf-8', newline='\n') as f:
    f.write(page)
print('top', data['top'], 'entries', sum(len(s['entries']) for s in data['sections'].values()), 'bytes', len(page))
