/* Public card facts are not holdings. This adapter deliberately drops the own,
 * bench and deck flags baked into the historical graph. Names have stable local
 * IDs; Oracle and printing IDs remain separate metadata, so hydration never
 * duplicates a physical copy. Search suggestions never auto-resolve an import.
 */
(function(root,factory){const classifier=typeof module==='object'&&module.exports?require('./card-classify.js'):root.MtgCardClassify;const api=factory(classifier);if(typeof module==='object'&&module.exports)module.exports=api;if(root)root.CrankCatalog=api;})(typeof globalThis!=='undefined'?globalThis:this,function(Classify){
  'use strict';
  const folded=s=>String(s||'').normalize('NFKC').trim().toLowerCase();
  function key(name){return 'card:'+btoa(String.fromCharCode(...new TextEncoder().encode(folded(name)))).replaceAll('+','-').replaceAll('/','_').replaceAll('=','');}
  function safeURL(raw){try{const u=new URL(raw);return u.protocol==='https:'?u.href:'';}catch{return '';}}
  function normalize(raw,prior={}){const c={...prior,...raw},name=String(c.name||'').trim();if(!name)throw Error('A card needs a name.');const type=c.typeLine||c.type_line||c.type||'',oracle=c.oracleText||c.oracle_text||'',identity=c.colorIdentity||c.color_identity||String(c.ci||'').split('');const tags=Classify.classify({typeLine:type,oracleText:oracle,keywords:c.keywords||[],card_faces:c.faces||c.card_faces||[]});const price=c.price===null?null:Number(c.price);return {id:key(name),oracleId:c.oracleId||c.oracle_id||'',scryfallId:c.scryfallId||'',name,typeLine:type,oracleText:oracle,manaCost:c.manaCost||c.mana_cost||'',manaValue:c.manaValue??c.cmc??c.mv??null,colorIdentity:identity,colors:c.colors||[],keywords:c.keywords||[],power:c.power??null,toughness:c.toughness??null,rarity:c.rarity||'',commander:!!(c.commander||c.isCommander||c.canBeCommander||(/Legendary/.test(type)&&/Creature/.test(type))||/can be your commander/i.test(oracle)),verified:c.verified??!!c.legalities?.commander,legalities:c.legalities||{},mechanics:raw.mechanics||tags.mechanics||[],roles:raw.roles||tags.roles||[],tribes:raw.tribes||tags.tribes||[],requires:raw.requires||tags.requires||[],causes:raw.causes||tags.causes||[],triggers:raw.triggers||tags.triggers||[],produces:raw.produces||tags.produces||[],price:Number.isFinite(price)&&price>0?price:null,priceUpdated:c.priceUpdated||'',priceSource:c.priceSource||'Scryfall snapshot',image:safeURL(c.imageLarge||c.normal||c.image||c.small||('https://api.scryfall.com/cards/named?exact='+encodeURIComponent(name)+'&format=image&version=normal')),set:c.setCode||c.set||'',setName:c.setName||'',collector:c.collector||c.collectorNumber||c.collector_number||'',commanderRank:c.commanderRank??null,rank:c.edhrecRank||c.rank||null,source:c.source||'Bundled Scryfall snapshot',updatedAt:c.updatedAt||'',url:safeURL(c.url||c.scryfallUri||c.scryfall_uri||''),gameChanger:!!(c.gameChanger||c.game_changer),layout:c.layout||'',faces:c.faces||c.card_faces||[]};}
  async function create(options){const byName=new Map(),byId=new Map();let graph=null,universeDate='',rankDate='',graphLoading=null;const fetcher=options.fetchImpl||fetch;
    function add(raw){const prior=byName.get(folded(raw.name)),next=normalize(raw,prior);byName.set(folded(next.name),next);byId.set(next.id,next);return next;}
    async function load(url){const cached=await options.repository?.cacheGet(url);try{const response=await fetcher(url,{cache:'default'});if(!response.ok)throw Error('HTTP '+response.status);const data=await response.json();options.repository?.cachePut(url,data).catch(()=>{});return data;}catch(error){if(cached)return cached;throw Error('The public card catalog is unavailable offline. Reconnect once to download it, or import a backup containing your cards. '+error.message);}}
    const settled=await Promise.allSettled([load(options.urls.universe),load(options.urls.cards),load(options.urls.facts),options.urls.ranks?load(options.urls.ranks):Promise.resolve(null)]);
    if(settled[0].status==='fulfilled'){const data=settled[0].value;universeDate=data.generatedAt;for(const [name,ci,rarity,mv,type,rank,commander] of data.cards)add({name,ci,rarity,mv,type,rank,commander:!!commander,verified:true,legalities:{commander:'legal'},updatedAt:universeDate});}
    if(settled[1].status==='fulfilled')for(const c of settled[1].value.cards)add(c);
    if(settled[2].status==='fulfilled')for(const [name,c] of Object.entries(settled[2].value.cards))add({name,...c});
    for(const c of Object.values(options.savedCards||{}))add(c);
    if(settled[3].status==='fulfilled'&&settled[3].value){const ranks=settled[3].value;rankDate=ranks.generatedAt;const ranked=new Map(ranks.cards.map(c=>[folded(c.name),c]));for(const c of [...byId.values()]){const match=ranked.get(folded(c.name))||ranked.get(folded(c.name.split(' // ')[0]));if(match)add({...c,commanderRank:match.rank});}}
    // An empty offline catalog must not prevent opening backup restore or User Functions.
    function search(query,{commander=false,mechanic='',rankMax=null,limit=80}={}){const q=folded(query),m=folded(mechanic);return [...byId.values()].filter(c=>(!commander||c.commander&&c.legalities.commander==='legal')&&(!q||folded(c.name).includes(q))&&(!m||folded([c.oracleText,...c.mechanics,...c.keywords,...c.roles].join(' ')).includes(m))&&(rankMax===null||c.commanderRank!==null&&c.commanderRank<=rankMax)).sort((a,b)=>(folded(a.name)===q?-1:folded(b.name)===q?1:0)||((commander?a.commanderRank:a.rank)||Infinity)-((commander?b.commanderRank:b.rank)||Infinity)||a.name.localeCompare(b.name)).slice(0,limit);}
    async function resolve(value,{signal,printing}={}){const name=String(value||'').trim();if(printing?.set&&printing?.collector){const found=await options.client.bySetNumber(printing.set,printing.collector,{signal});if(!found)return null;if(folded(found.name)!==folded(name))throw Error(`That printing is ${found.name}, not ${name}. Review the row before import.`);return add({...found,collector:printing.collector,verified:true,source:'Scryfall exact printing',updatedAt:new Date().toISOString()});}const local=byName.get(folded(name));if(local)return local;if(/^https?:\/\//i.test(name)){const result=await options.link.resolveLink(name,{client:options.client,allowManual:false,signal});return result.card?add({...result.card,verified:true,source:name,updatedAt:new Date().toISOString()}):null;}const found=await options.client.named(name,{exact:true,signal});return found?add({...found,verified:true,source:'Scryfall exact name',updatedAt:new Date().toISOString()}):null;}
    async function details(c,{signal}={}){if(c.verified&&c.oracleText&&c.manaCost!==undefined)return c;try{const raw=await options.client.named(c.name,{exact:true,signal});return raw?add({...raw,verified:true,source:'Scryfall exact name',updatedAt:new Date().toISOString()}):c;}catch{return c;}}
    async function loadGraph(){if(graph)return graph;if(!graphLoading)graphLoading=load(options.urls.graph).then(data=>{graph=data;for(const c of data.cards){const prior=byName.get(folded(c.name));add({...c,oracleId:c.id,legalities:prior?.legalities||{commander:'legal'},verified:true});}return data;}).catch(error=>{graphLoading=null;throw error;});return graphLoading;}
    return {add,search,resolve,details,loadGraph,exact:name=>byName.get(folded(name))||null,get:id=>byId.get(id)||null,all:()=>[...byId.values()],load,universeDate,rankDate,available:()=>byId.size};
  }
  return {key,folded,normalize,safeURL,create};
});
