/* A bounded, navigable neighborhood of actual catalog relationships. Typed
 * structural edges and EDHREC co-play are kept distinct from simulated evidence.
 * Canvas has an equivalent keyboard-accessible neighbor list supplied by UI. */
(function(root){'use strict';root.CrankGraph={mount({canvas,cards,played=[],focus,onSelect,onNeighbors,type='mechanic'}){const ctx=canvas.getContext('2d'),byId=new Map(cards.map(c=>[c.id,c])),trail=[];let center=focus||cards[0]?.id,nodes=[],scale=1,pan={x:0,y:0},drag=null,width=600,height=550,frame=0,disposed=false;
function links(c){if(!c)return[];if(type==='played')return played.filter(e=>e.from===c.id||e.to===c.id).map(e=>({card:byId.get(e.from===c.id?e.to:e.from),reason:`EDHREC co-play · ${e.decks} decks · ${(e.inclusion*100).toFixed(1)}% inclusion`})).filter(e=>e.card).slice(0,12);const generic=new Set(['creatures','lands','artifacts','enchantments','instants','sorceries','planeswalkers']),terms=new Set([...(c.mechanics||[]),...(c.roles||[]).filter(x=>!generic.has(x))]);return cards.filter(x=>x.id!==c.id).map(x=>{const shared=[...(x.mechanics||[]),...(x.roles||[]).filter(t=>!generic.has(t))].filter(t=>terms.has(t)),feeds=(c.produces||[]).filter(t=>(x.requires||[]).includes(t)),fed=(c.requires||[]).filter(t=>(x.produces||[]).includes(t));return {card:x,shared,score:shared.length*2+(feeds.length+fed.length)*3,reason:feeds.length?'Produces → needs · '+feeds.join(', '):fed.length?'Needs ← produces · '+fed.join(', '):'Shared mechanics / roles · '+shared.slice(0,3).join(', ')};}).filter(x=>x.score).sort((a,b)=>b.score-a.score||a.card.name.localeCompare(b.card.name)).slice(0,12);}
function layout(){const c=byId.get(center),neighbors=links(c);nodes=c?[{card:c,x:0,y:0,r:39},...neighbors.map((n,i)=>({card:n.card,reason:n.reason,x:Math.cos(i/neighbors.length*Math.PI*2)*220,y:Math.sin(i/neighbors.length*Math.PI*2)*180,r:22}))]:[];onNeighbors?.(c,neighbors,trail.length);draw();}
function resize(){const r=canvas.getBoundingClientRect();width=r.width;height=r.height;const d=Math.min(devicePixelRatio||1,2);canvas.width=width*d;canvas.height=height*d;ctx.setTransform(d,0,0,d,0,0);draw();}
function draw(){if(disposed)return;cancelAnimationFrame(frame);frame=requestAnimationFrame(()=>{ctx.clearRect(0,0,width,height);ctx.save();ctx.translate(width/2+pan.x,height/2+pan.y);ctx.scale(scale,scale);for(const n of nodes.slice(1)){ctx.beginPath();ctx.moveTo(0,0);ctx.lineTo(n.x,n.y);ctx.strokeStyle=type==='played'?'#c6a86d88':'#5384b677';ctx.lineWidth=1;ctx.stroke();}for(const [i,n] of nodes.entries()){const glow=ctx.createRadialGradient(n.x,n.y,0,n.x,n.y,n.r+12);glow.addColorStop(0,i?'#385b83':'#638abd');glow.addColorStop(1,'#263c5700');ctx.fillStyle=glow;ctx.beginPath();ctx.arc(n.x,n.y,n.r+12,0,Math.PI*2);ctx.fill();ctx.fillStyle=i?'#203a58':'#386794';ctx.strokeStyle=i?'#71b6e3':'#c0e8ff';ctx.beginPath();ctx.arc(n.x,n.y,n.r,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.fillStyle='#edf7ff';ctx.font=(i?'11':'bold 13')+'px Satoshi, sans-serif';ctx.textAlign='center';const name=n.card.name;ctx.fillText(name.length>28?name.slice(0,26)+'…':name,n.x,n.y+n.r+17);ctx.fillStyle='#bddbff';ctx.font='12px Satoshi, sans-serif';ctx.fillText((n.card.ci||'C').split('').join(' '),n.x,n.y+4);}ctx.restore();});}
function pick(e){const r=canvas.getBoundingClientRect(),x=(e.clientX-r.left-width/2-pan.x)/scale,y=(e.clientY-r.top-height/2-pan.y)/scale;return nodes.find(n=>Math.hypot(n.x-x,n.y-y)<n.r+8);}
function select(id,history=true){if(!byId.has(id))return;if(history&&id!==center)trail.push(center);center=id;scale=1;pan={x:0,y:0};layout();onSelect?.(byId.get(id));}
function wheel(e){e.preventDefault();const r=canvas.getBoundingClientRect(),x=e.clientX-r.left-width/2,y=e.clientY-r.top-height/2,old=scale;scale=Math.max(.35,Math.min(3,scale*Math.exp(-e.deltaY*.001)));pan.x=x-(x-pan.x)*scale/old;pan.y=y-(y-pan.y)*scale/old;draw();}
function down(e){drag={x:e.clientX,y:e.clientY,px:pan.x,py:pan.y,moved:false};canvas.setPointerCapture(e.pointerId);}
function move(e){if(!drag)return;const dx=e.clientX-drag.x,dy=e.clientY-drag.y;drag.moved=drag.moved||Math.hypot(dx,dy)>5;pan={x:drag.px+dx,y:drag.py+dy};draw();}
function up(e){if(drag&&!drag.moved){const n=pick(e);if(n)select(n.card.id);}drag=null;}
function key(e){if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','+','-','0'].includes(e.key)){e.preventDefault();if(e.key==='0'){scale=1;pan={x:0,y:0};}else if(e.key==='+')scale=Math.min(3,scale*1.2);else if(e.key==='-')scale=Math.max(.35,scale/1.2);else {pan.x+=e.key==='ArrowLeft'?25:e.key==='ArrowRight'?-25:0;pan.y+=e.key==='ArrowUp'?25:e.key==='ArrowDown'?-25:0;}draw();}}
canvas.addEventListener('wheel',wheel,{passive:false});canvas.addEventListener('pointerdown',down);canvas.addEventListener('pointermove',move);canvas.addEventListener('pointerup',up);canvas.addEventListener('pointercancel',up);canvas.addEventListener('keydown',key);const observer=new ResizeObserver(resize);observer.observe(canvas);layout();resize();return {select,back(){if(trail.length)select(trail.pop(),false);},setType(value){type=value;layout();},reset(){scale=1;pan={x:0,y:0};draw();},destroy(){disposed=true;cancelAnimationFrame(frame);observer.disconnect();for(const [name,fn] of [['wheel',wheel],['pointerdown',down],['pointermove',move],['pointerup',up],['pointercancel',up],['keydown',key]])canvas.removeEventListener(name,fn);}};}};})(globalThis);
