/* Shared production shell. All visible mutations follow a committed transaction;
 * browser navigation never creates holdings and static reference data stays opt-in.
 * Feature modules receive this context rather than keeping a second state store. */
(async function(){'use strict';
const M=CrankCollection,E=CrankExchange,$=(s,r=document)=>r.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const main=$('#cm-main'),dialog=$('#cm-dialog'),actions={},views={};let state=M.empty(),repo,catalog,glossary,disposeView=null,renderSeq=0,noticeTimer,committing=false,mirror=null;
const uid=()=>crypto.randomUUID(),money=n=>n===null||n===undefined?'Unknown':'$'+Number(n).toFixed(2),source=s=>({owned:'Owned',ordered:'Ordered',incoming:'Incoming trade','to-buy':'To buy',draft:'Draft list'}[s]||s);
function colors(ci){return `<span class="cm-colors" aria-label="${esc((ci||[]).join(', ')||'Colorless')}">${(ci||[]).map(x=>`<i class="cm-color ${esc(x)}" title="${esc({W:'White',U:'Blue',B:'Black',R:'Red',G:'Green'}[x]||x)}"></i>`).join('')||'C'}</span>`;}
function mana(cost){return `<span class="cm-mana" aria-label="Mana cost ${esc(cost||'unknown')}">${(String(cost||'').match(/\{[^}]+\}/g)||[]).map(x=>/^[WUBRG23]$/.test(x.slice(1,-1))?`<img src="assets/mana/${x.slice(1,-1)}.svg?v=1" alt="${esc(x)}" width="19" height="19">`:`<span class="cm-mana-symbol" title="${esc(x)}">${esc(x.slice(1,-1))}</span>`).join('')}</span>`;}
function button(label,action,data={},primary=false){return `<button type="button" class="v-button${primary?' primary':''}" data-action="${esc(action)}" ${Object.entries(data).map(([k,v])=>`data-${k}="${esc(v)}"`).join(' ')}>${esc(label)}</button>`;}
function options(items,value){return items.map(x=>{const [v,l]=Array.isArray(x)?x:[x,x];return `<option value="${esc(v)}"${String(v)===String(value)?' selected':''}>${esc(l)}</option>`;}).join('');}
function field(label,name,value='',attrs=''){return `<label>${esc(label)}<input name="${esc(name)}" value="${esc(value)}" ${attrs}></label>`;}
function select(label,name,items,value){return `<label>${esc(label)}<select name="${esc(name)}" aria-label="${esc(label)}">${options(items,value)}</select></label>`;}
function note(text,warn=false){return `<div class="cm-note${warn?' cm-warning':''}">${esc(text)}</div>`;}
function head(kicker,title,description,controls=''){return `<header class="cm-page-head"><div><div class="v-eyebrow">${esc(kicker)}</div><h1>${esc(title)}</h1><p>${esc(description)}</p></div><div class="cm-actions">${controls}</div></header>`;}
function notice(message,error=false){const el=$('#cm-notice');el.textContent=message;el.classList.toggle('error',error);el.hidden=false;clearTimeout(noticeTimer);noticeTimer=setTimeout(()=>el.hidden=true,error?18000:7000);}
function modal(title,body){if(dialog.open)dialog.close();dialog.innerHTML=`<div class="cm-dialog-head"><h2 id="cm-dialog-title">${esc(title)}</h2><button type="button" class="cm-dialog-close" data-action="close" aria-label="Close dialog">×</button></div>${body}`;dialog.setAttribute('aria-labelledby','cm-dialog-title');dialog.showModal();return dialog;}
function form(title,body,submit,label='Save changes'){const d=modal(title,`<form class="cm-form"><div class="cm-form-grid">${body}</div><p class="cm-error" hidden role="alert"></p><div class="cm-form-footer">${button('Cancel','close')}<button class="v-button primary" type="submit">${esc(label)}</button></div></form>`);const baseRevision=state.revision,f=$('form',d);f.addEventListener('submit',async e=>{e.preventDefault();if(!f.reportValidity())return;const b=$('[type=submit]',f),error=$('.cm-error',f);b.disabled=true;error.hidden=true;try{if(baseRevision!==state.revision)throw Error('The library changed while this form was open. Close it and review the current records before retrying.');await submit(Object.fromEntries(new FormData(f)),f);if(dialog.contains(f)&&dialog.open)dialog.close();}catch(err){error.textContent=err.message;error.hidden=false;}finally{b.disabled=false;}});return f;}
function route(){const raw=location.hash.slice(1)||({ 'matrix.html':'collection','graph.html':'discover'}[location.pathname.split('/').pop()]||'decks'),[view,q='']=raw.split('?');return {view:views[view]?view:'decks',params:new URLSearchParams(q)};}
function go(view,params={}){const q=new URLSearchParams(Object.entries(params).filter(([,v])=>v!==''&&v!==null&&v!==undefined));const hash='#'+view+(q.size?'?'+q:'');if(location.hash===hash)render();else location.hash=hash;}
async function render(){if(!catalog)return;disposeView?.();disposeView=null;glossary?.hide();const seq=++renderSeq,r=route();document.querySelectorAll('[data-nav]').forEach(el=>el.setAttribute('aria-current',el.dataset.nav===r.view?'page':'false'));try{const cleanup=await views[r.view](r.params);if(seq===renderSeq)disposeView=cleanup||null;else cleanup?.();}catch(err){if(seq===renderSeq)main.innerHTML=head('Unable to open this view','Your saved library is intact',err.message,button('My Decks','home'));}status();}
function status(){if(repo)$('#cm-save-status').textContent=`Saved locally · revision ${state.revision}${navigator.onLine?'':' · offline'}`;}
async function refresh(){state=await repo.getState();for(const c of Object.values(state.cards))catalog?.add(c);await render();}
async function commit(command,{renderView=true}={}){if(committing)throw Error('A save is already in progress. Please wait for its receipt.');committing=true;$('#cm-save-status').textContent='Saving…';try{const result=await repo.commit({id:uid(),...command},state.revision);state=result.state;for(const c of Object.values(state.cards))catalog.add(c);notice(result.summary);if(renderView)await render();else status();await writeMirror();return result;}catch(error){state=await repo.getState();status();throw error;}finally{committing=false;}}
function download(name,content,type='application/json'){const a=document.createElement('a'),url=URL.createObjectURL(new Blob([content],{type}));a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);}
async function writeMirror(){if(!mirror)return;try{if(await mirror.queryPermission({mode:'readwrite'})!=='granted')return notice('Library saved locally; backup mirror needs permission again.',true);const data=await E.backup(await repo.exportData()),w=await mirror.createWritable();await w.write(JSON.stringify(data));await w.close();}catch(e){notice('Library saved locally. Backup mirror failed: '+e.message,true);}}
function readableLocation(l){return l.location?.kind==='deck'?`Physically in ${M.deck(state,l.location.deckId).name} (${l.location.box||'deck box'})`:l.source==='owned'?`Bench${l.location?.box?' · '+l.location.box:''}`:'Not received';}
function affected(l){return `${source(l.source)} · ${l.quantity} copies · ${readableLocation(l)}${l.allocation?' · Reserved to '+M.deck(state,l.allocation.deckId).name:''}${l.offer!=='none'?' · Sell / Trade: '+l.offer:''}${l.allocation&&M.deck(state,l.allocation.deckId).locked?' · Locked deck':''}`;}
function review(title,body,command){const planned={id:uid(),confirmed:true,...command};const preview=M.apply(state,planned);const before=M.counters(state),after=M.counters(preview.state);return form(title,`<div class="cm-full">${body}${note(preview.summary)}${effectsHTML(preview.event.effects,preview.state)}<p>Owned ${before.owned} → ${after.owned} · Ordered ${before.ordered} → ${after.ordered} · To buy ${before.toBuy} → ${after.toBuy}</p></div>`,()=>commit(planned),'Confirm change');}
function effectsHTML(effects,after){if(!effects?.length)return '';const label=l=>l?`${l.quantity} ${source(l.source)} · ${l.allocation?(after.decks.find(d=>d.id===l.allocation.deckId)?.name||'Deck'):'Unassigned'} · ${l.location?.kind==='deck'?'physically in '+(after.decks.find(d=>d.id===l.location.deckId)?.name||'deck box'):l.source==='owned'?'Bench':'not received'}`:'No record';return `<details class="cm-details"><summary>${effects.length} copy / allocation changes</summary><ul>${effects.map(change=>`<li><strong>${esc(after.cards[(change.after||change.before).cardId]?.name||'Card')}</strong>: ${esc(label(change.before))} → ${esc(label(change.after))}</li>`).join('')}</ul></details>`;}
async function cardPicker(title,onPick,{commander=false}={}){const d=modal(title,`<label>Card name or a Scryfall link<input id="cm-card-query" autocomplete="off" placeholder="Start typing a name"></label><div class="cm-commander-results" id="cm-card-results"></div><div class="cm-actions">${button('Search exact name / link','picker-resolve')}</div><p class="cm-muted">Suggestions never change ownership. If the exact name cannot be found, provide the card’s Scryfall link.</p><p class="cm-error" hidden></p>`);const input=$('#cm-card-query',d),results=$('#cm-card-results',d);const choose=async c=>{if(commander&&!c.commander)throw Error('That card is not a verified commander.');await onPick(c);};function show(){results.innerHTML=catalog.search(input.value,{commander,limit:30}).map(c=>`<button type="button" class="cm-commander-result" data-pick-card="${esc(c.id)}"><strong>${esc(c.name)}</strong>${colors(c.colorIdentity)}<span>${esc((c.mechanics[0]||c.keywords[0]||c.typeLine.split('—')[0]).slice(0,28))}</span></button>`).join('');}input.addEventListener('input',show);results.addEventListener('click',e=>{const b=e.target.closest('[data-pick-card]');if(b)choose(catalog.get(b.dataset.pickCard)).catch(error=>{const el=$('.cm-error',d);el.hidden=false;el.textContent=error.message;});});actions['picker-resolve']=async()=>{const c=await catalog.resolve(input.value);if(!c)throw Error('No exact match. Check the name or provide its Scryfall card link.');await choose(c);};show();input.focus();}
async function inspector(id){let c=state.cards[id]||catalog.get(id);if(!c)throw Error('Card not found.');c=await catalog.details(c);modal(c.name,`<div class="cm-inspector">${c.image?`<img src="${esc(c.image)}" alt="${esc(c.name)}" loading="lazy">`:'<div class="cm-note">Card image unavailable offline</div>'}<div><p>${mana(c.manaCost)} ${c.power!==null?esc(c.power+'/'+c.toughness):''}</p><p>${glossary.html(c.typeLine)}</p><div class="cm-oracle">${glossary.html(c.oracleText||'Full rules text has not been cached for this card.')}</div><p>${colors(c.colorIdentity)} · ${money(c.price)} <small>${esc(c.priceUpdated||'Snapshot date not supplied')}</small></p><p class="cm-muted">${esc(c.source)} · ${c.verified?'Verified catalog identity':'Unverified identity'}</p></div></div><h3>Your copies and commitments</h3><div>${M.projection(state).filter(r=>r.cardId===id).map(r=>`<p>${esc(source(r.source))} · ${r.quantity} · ${esc(r.placement)} ${r.deckId?'· '+esc(M.deck(state,r.deckId).name):''} ${r.kind==='lot'?'· '+esc(readableLocation(r)):''}</p>`).join('')||'<p>No library copies or commitments.</p>'}</div><div class="cm-actions">${button('Add copies','add-card',{card:id},true)}${button('Explore connections','discover-card',{card:id})}</div>`);}
const C={M,E,$,esc,uid,money,source,colors,mana,button,options,field,select,note,head,notice,modal,form,go,route,render,refresh,commit,download,review,cardPicker,inspector,affected,readableLocation,actions,views,main,get state(){return state;},get repo(){return repo;},get catalog(){return catalog;},get glossary(){return glossary;},setState(value){state=value;}};
actions.close=()=>dialog.close();actions.home=()=>go('decks');actions.card=el=>inspector(el.dataset.card);actions['discover-card']=el=>{dialog.close();go('discover',{card:el.dataset.card});};actions['reset-picks']=()=>commit({type:'preferences',values:{comparisonPicks:[]}});
actions.backup=async()=>{download('CrankMagic-backup-'+new Date().toISOString().slice(0,10)+'.json',JSON.stringify(await E.backup(await repo.exportData()),null,2));notice('Full backup exported. Keep it outside browser storage.');};
actions.mirror=async()=>{if(!window.showSaveFilePicker){notice('This browser does not support a writable backup mirror. Use Export a full backup.');return;}mirror=await showSaveFilePicker({suggestedName:'CrankMagic-mirror.json',types:[{description:'CrankMagic backup',accept:{'application/json':['.json']}}]});await repo.writeMeta('mirror',mirror);await writeMirror();notice('Backup mirror connected for this session. Every successful change will update it.');};
actions.undo=async()=>{state=await repo.undo(state.revision);await render();await writeMirror();notice('Last change undone.');};
actions.history=async()=>{const rows=await repo.history();modal('History & undo',`${note('History records completed transactions. Undo reverses the last compound change when no later change has intervened.')}${button('Undo last change','undo')}<label style="margin-top:16px">Filter history<input id="cm-history-filter" placeholder="Card, deck or operation"></label><div id="cm-history-rows"></div>`);const draw=()=>{$('#cm-history-rows').innerHTML=rows.filter(r=>(r.summary+' '+r.type).toLowerCase().includes($('#cm-history-filter').value.toLowerCase())).slice(0,200).map(r=>`<article><h3>${esc(r.summary)}</h3><p class="cm-muted">${esc(r.at)} · revision ${r.revision} · ${esc(r.type)}</p>${effectsHTML(r.effects,state)}</article>`).join('')||'<p>No matching history.</p>';};$('#cm-history-filter').addEventListener('input',draw);draw();};
actions.clear=()=>form('Clear all CrankMagic data',`<div class="cm-full">${note('This permanently removes the library, decks, history, undo data and cached public card data from this browser. Export a backup first. It does not delete files you exported.',true)}${button('Export backup first','backup')}</div>${field('Type CLEAR to confirm','confirm','','required autocomplete="off"')}<label class="cm-checkbox"><input type="checkbox" name="legacy">Also remove this app’s legacy storage keys</label>`,async data=>{if(data.confirm!=='CLEAR')throw Error('Type CLEAR exactly.');state=await repo.clear(state.revision);if(data.legacy)for(const key of MtgUserState.keys())localStorage.removeItem(key);mirror=null;catalog=await CrankCatalog.create({repository:repo,client:MtgScryfall.createClient(),link:MtgCardLink,urls:CrankAssets,savedCards:{}});await render();notice('Local library and history cleared. Exported files remain under your control.');},'Clear local data');
document.addEventListener('click',async e=>{const el=e.target.closest('[data-action]');if(!el||el.disabled)return;const fn=actions[el.dataset.action];if(!fn)return;e.preventDefault();try{await fn(el,e);}catch(error){if(error.name!=='AbortError')notice(error.message,true);}});
$('#cm-user-menu').addEventListener('beforetoggle',e=>{if(e.newState==='open'){const r=$('#cm-user-functions').getBoundingClientRect(),m=$('#cm-user-menu');m.style.right='16px';m.style.left='auto';m.style.top=(r.bottom+8)+'px';}});$('#cm-user-menu').addEventListener('click',e=>{if(e.target.closest('[data-action]'))$('#cm-user-menu').hidePopover();});
window.addEventListener('hashchange',()=>{render();main.focus({preventScroll:true});});window.addEventListener('online',status);window.addEventListener('offline',status);
try{repo=await CrankRepository.open();state=await repo.getState();catalog=await CrankCatalog.create({repository:repo,client:MtgScryfall.createClient(),link:MtgCardLink,urls:CrankAssets,savedCards:state.cards});let terms=[];try{terms=(await catalog.load(CrankAssets.glossary)).entries;}catch(e){notice(e.message,true);}glossary=CrankGlossary.create(terms);for(const module of globalThis.CrankFeatures||[])module(C);repo.subscribe(async info=>{if(info.closed)return notice('Local database was upgraded in another tab. Reload before editing.',true);if(!committing&&info.revision!==state.revision){await refresh();notice('Library refreshed after a change in another tab. Review any open form before saving.');}});await render();if(navigator.storage?.persist)navigator.storage.persist().catch(()=>{});if('serviceWorker' in navigator)navigator.serviceWorker.register('crankmagic-sw.js?v=1',{scope:'./'}).catch(error=>notice('Offline app caching is unavailable: '+error.message,true));}
catch(error){main.innerHTML=head('Local storage unavailable','Your data has not been changed',error.message)+note('CrankMagic requires HTTPS or localhost and browser storage. Reopen it on its static site with storage enabled.',true);}
})();
