import {chromium,launchOptions,packageRoot,qaRoot} from './environment.mjs';
import {readFileSync} from 'node:fs';
import assert from 'node:assert/strict';
const dir=packageRoot;
const fragment=packageRoot+'/fragment.html';
const browser=await chromium.launch(launchOptions);
let checks=0;const errors=[];
function ok(v,n){assert.ok(v,n);checks++;}
try{
 const page=await browser.newPage({viewport:{width:1200,height:1000}});page.on('pageerror',e=>errors.push(e.message));await page.route(/^https?:/,r=>r.abort());
 const nav=async v=>page.locator('[data-view='+v+']').click();
 const fresh=async()=>{await page.setContent(readFileSync(fragment,'utf8'));await page.evaluate(()=>document.fonts.ready);};
 await fresh();ok(!errors.length,errors.join(','));
 await nav('lab');ok(await page.locator('#v-start option').count()===2,'commander selection and existing-list paths');
 await page.locator('.v-mechanics summary').click();await page.locator('[data-mechanic][value=Proliferate]').check();await page.locator('[data-mechanic][value=Tokens]').check();ok((await page.locator('#v-entry-summary').innerText()).includes('Proliferate, Tokens'),'mechanics feed summary');
 await page.locator('#v-start').selectOption('commander');ok(await page.locator('#v-commander-name').isVisible(),'commander input');
 await page.locator('#v-commander-name').fill('Atraxa');await page.locator('#v-find-commander').click();await page.locator('[data-commander-result]').click();ok((await page.locator('#v-entry-summary').innerText()).includes("Atraxa, Praetors' Voice"),'commander selected');
 await page.locator('#v-commander-name').fill('Uncatalogued commander');await page.locator('#v-find-commander').click();ok(await page.locator('#v-link-entry').isVisible(),'name miss offers link');
 await page.locator('#v-commander-link').fill('javascript:alert(1)');await page.locator('#v-save-link').click();ok((await page.locator('#v-commander-result').innerText()).includes('http'),'unsafe scheme rejected');
 await page.locator('#v-commander-link').fill('https://scryfall.com/card/example/1');await page.locator('#v-save-link').click();ok((await page.locator('#v-entry-summary').innerText()).includes('unresolved'),'link cannot become trusted metadata');await page.locator('#v-save-link').click();ok((await page.locator('#v-commander-result').innerText()).includes('1 record.'),'same link not duplicated');
 await page.locator('#v-salt').fill('1');ok((await page.locator('#v-salt-description').innerText()).includes('Extremely friendly'),'saltiness low');await page.locator('#v-salt').fill('5');ok((await page.locator('#v-salt-description').innerText()).includes('Any legal mechanic; optimize to win'),'saltiness high');
 await page.locator('#v-start').selectOption('list');await page.locator('#v-lab-create-group').click();ok(await page.locator('#v-dialog').isVisible(),'create group dialog');
 const bounds=await page.locator('#v-dialog').boundingBox();ok(bounds.x>=0&&bounds.y>=0&&bounds.x+bounds.width<=1200&&bounds.y+bounds.height<=1000,'dialog fits viewport');
 await page.locator('#v-group-name').fill('Test list');await page.locator('#v-group-commander').fill("Atraxa, Praetors' Voice");await page.locator('#v-group-text').fill('1.5 Sol Ring');await page.locator('#v-review-group').click();ok(await page.locator('#v-save-group').isDisabled(),'fraction rejected');
 await page.locator('#v-group-file').setInputFiles({name:'list.csv',mimeType:'text/csv',buffer:Buffer.from('Name,Quantity\n"Atraxa, Praetors\' Voice",1\nIsland,99')});await page.locator('#v-review-group').click();ok((await page.locator('#v-group-review').innerText()).includes('100 cards · 0 new owned'),'quoted CSV and quantity');await page.locator('#v-save-group').click();ok((await page.locator('#v-list-readiness').innerText()).includes('100 / 100'),'selected new group');
 await nav('collection');ok((await page.locator('#v-roster-counts').innerText()).includes('5owned'),'import creates no holdings');ok(await page.locator('#v-roster tbody tr[data-record]').count()===2,'new group rows');ok((await page.locator('#v-roster tbody').innerText()).includes('99 planned'),'quantities preserved');await page.locator('#v-show-all-collection').click();ok(await page.locator('#v-roster tbody tr[data-record]').count()===10,'clear all returns master plus drafts');
 await fresh();await page.locator('#v-open-atraxa').click();ok(await page.locator('[data-screen=overview]').isVisible(),'deck opens overview');ok(await page.locator('.v-composition').isVisible(),'composition');ok((await page.locator('#v-overview').innerText()).includes('How to play'),'play guide');ok((await page.locator('#v-overview').innerText()).includes('not simulation results'),'SWOT evidence label');
 await page.locator('#v-overview-cards').click();ok(await page.locator('#v-collection-group').inputValue()==='deck:Atraxa','deck filter applied');ok(await page.locator('#v-roster tbody tr[data-record]').count()===3,'only deck records');await page.locator('#v-roster [data-filter-toggle]').click();await page.locator('#v-roster [data-clear-filters]').click();ok(await page.locator('#v-roster tbody tr[data-record]').count()===8,'table clear breaks deck scope');
 await nav('decks');await page.locator('#v-open-krenko').click();ok((await page.locator('#v-overview h1').innerText()).includes('Krenko'),'second overview different');await page.locator('#v-overview-tune').click();ok(await page.locator('#v-start').inputValue()==='list'&&await page.locator('#v-input-group').inputValue()==='deck:Krenko','tune keeps deck input');
 await nav('shop');await page.locator('[data-shop-mode=assembly]').click();ok((await page.locator('#v-shop .v-source-label').allTextContents()).every(v=>v==='Owned'),'assembly shows owned');await page.locator('[data-shop-mode=buying]').click();
 const menu=page.locator('#v-shop [data-row-menu=signet]');await menu.locator('summary').click();await menu.locator('[data-command=receive]').click();await menu.locator('summary').click();await menu.locator('[data-sub-toggle]').hover();ok(await menu.locator('.v-deck-submenu').isVisible(),'hover submenu');const primary=await menu.locator('.v-menu-options').boundingBox(),sub=await menu.locator('.v-deck-submenu').boundingBox();ok(sub.x+sub.width<=primary.x+8,'submenu opens left');await menu.locator('[data-box-deck=Atraxa]').click();await nav('collection');ok((await page.locator('#v-roster [data-record=signet]').innerText()).includes('In deck'),'chosen destination placed');
 const correct=page.locator('#v-roster [data-row-menu=signet]');await correct.locator('summary').click();await correct.locator('[data-command=order]').click();ok((await page.locator('#v-dialog').innerText()).includes('removes the owned claim'),'backward correction explains ownership');await page.locator('#v-confirm-change').click();ok((await page.locator('#v-roster [data-record=signet]').innerText()).includes('Ordered')&&!(await page.locator('#v-roster [data-record=signet]').innerText()).includes('In deck'),'backward correction consistent');
 await nav('decks');await page.locator('#v-undo').click();await nav('collection');ok((await page.locator('#v-roster [data-record=signet]').innerText()).includes('In deck'),'undo restores correction');
 await correct.locator('summary').click();await correct.locator('[data-sub-toggle]').click();await correct.locator('[data-box-deck=Krenko]').click();ok(await page.locator('#v-placement-slot').isVisible(),'different deck requires replacement slot');await page.locator('#v-review-placement').click();ok((await page.locator('#v-dialog').innerText()).includes('locked allocation'),'destination lock warning');await page.locator('#v-confirm-change').click();ok((await page.locator('#v-roster [data-record=signet]').innerText()).includes('Krenko'),'chosen new deck placed');ok((await page.locator('#v-roster-counts').innerText()).includes('6owned'),'physical swap conserves ownership');await nav('decks');await page.locator('#v-undo').click();await nav('collection');ok((await page.locator('#v-roster [data-record=signet]').innerText()).includes('Atraxa'),'undo restores both decks');
 await nav('discover');await page.locator('[data-node=atraxa]').waitFor();await page.locator('#v-graph').scrollIntoViewIfNeeded();const g=await page.locator('#v-graph').boundingBox();await page.mouse.move(g.x+g.width/2,g.y+g.height/2);const oldTransform=await page.locator('#v-world').getAttribute('style');await page.mouse.wheel(0,-220);await page.waitForTimeout(80);ok(await page.locator('#v-world').getAttribute('style')!==oldTransform,'wheel zoom');const zoomed=await page.locator('#v-world').getAttribute('style');await page.mouse.move(5,10);await page.mouse.wheel(0,160);await page.waitForTimeout(80);ok(await page.locator('#v-world').getAttribute('style')===zoomed,'wheel outside does not zoom');
 for(const width of [1024,736,390,320])for(const theme of ['light','dark']){await page.setViewportSize({width,height:1000});await page.emulateMedia({colorScheme:theme});await fresh();await page.locator('#v-open-atraxa').click();ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'overview fits '+width);if([1024,390].includes(width))await page.screenshot({path:qaRoot+'/v4-overview-'+width+'-'+theme+'.png',fullPage:true});await nav('lab');await page.locator('#v-start').selectOption('commander');await page.locator('.v-mechanics summary').click();ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'lab fits '+width);if([1024,390].includes(width))await page.screenshot({path:qaRoot+'/v4-lab-'+width+'-'+theme+'.png',fullPage:true});await page.locator('#v-start').selectOption('list');await page.locator('#v-lab-create-group').click();const d=await page.locator('#v-dialog').boundingBox();ok(d.x>=0&&d.x+d.width<=width&&d.y>=0&&d.y+d.height<=1000,'dialog fits '+width+' '+JSON.stringify(d));await page.keyboard.press('Escape');}
 await page.setViewportSize({width:1200,height:1000});await fresh();ok((await page.locator('.v-top').innerText()).includes('CrankMagic'),'new app name');ok((await page.locator('#v-open-atraxa').innerText()).includes('Counters · Proliferate'),'deck mechanic label');await page.locator('[data-archive-deck=Atraxa]').click();await page.locator('#v-confirm-change').click();ok(!await page.locator('#v-open-atraxa').isVisible(),'archived deck removed from shelf');await nav('collection');ok((await page.locator('#v-roster-counts').innerText()).includes('5owned'),'archive conserves holdings');ok((await page.locator('#v-roster [data-record=sol]').innerText()).includes('Move pending'),'archive preserves physical move task');const archiveMenu=page.locator('#v-roster [data-row-menu=sol]');await archiveMenu.locator('summary').click();await archiveMenu.locator('[data-sub-toggle]').click();ok(await archiveMenu.locator('[data-box-deck=Atraxa]').count()===0,'archived deck excluded from allocation choices');await page.keyboard.press('Escape');await nav('lab');await page.locator('#v-start').selectOption('list');ok(await page.locator('#v-input-group option[value="deck:Atraxa"]').count()===0,'archived deck excluded from build choices');await nav('decks');await page.locator('#v-show-archived').click();ok((await page.locator('#v-archived-list').innerText()).includes('Atraxa'),'archived list retained');await page.locator('#v-archive-undo').click();ok(await page.locator('#v-open-atraxa').isVisible(),'undo archive restores deck');await nav('collection');ok((await page.locator('#v-roster [data-record=sol]').innerText()).includes('In deck'),'undo archive restores copy allocation');
 ok(await page.locator('.v-brand-subline').innerText()==='An Intelligent MtG: Commander Deck Creator & Card Libary','final subline exact');
 await fresh();const originalCounts=await page.locator('#v-counts').innerText();
 const replacementMenu=page.locator('#v-slots [data-row-menu=sphere]');await replacementMenu.locator('summary').click();await replacementMenu.locator('[data-command=replace]').click();await page.locator('#v-candidate').selectOption('chalice');await page.locator('#v-transfer').click();
 ok((await page.locator('#v-dialog').innerText()).includes('leaves Krenko needing another copy'),'protected donor shortfall disclosed');
 await page.locator('#v-confirm-change').click();await nav('collection');
 ok((await page.locator('#v-roster [data-record=chalice]').innerText()).includes('Atraxa'),'protected transfer permitted after review');
 ok((await page.locator('#v-roster-counts').innerText()).includes('5owned'),'protected transfer conserves holdings');
 await nav('decks');ok(await page.locator('#v-krenko-lock').innerText()==='Locked','copy override retains donor lock');await page.locator('#v-undo').click();ok(await page.locator('#v-counts').innerText()===originalCounts,'transfer undo restores counts');
 ok(!errors.length,errors.join(','));console.log(checks+' new-flow checks passed: entry paths, mechanics, link trust, CSV intake, collection scopes, overview, reversible source, assembly, submenu, wheel zoom, archive and protected-copy override.');
}finally{await browser.close();}
