import {chromium,launchOptions,packageRoot,qaRoot} from './environment.mjs';import {readFileSync,writeFileSync} from 'node:fs';import {pathToFileURL} from 'node:url';import assert from 'node:assert/strict';
const root=packageRoot,url=pathToFileURL(root+'/mtg-facelift-mockup.html').href;
let checks=0;const errors=[],ok=(v,m)=>{assert.ok(v,m);checks++;};const browser=await chromium.launch(launchOptions);
try{
 const page=await browser.newPage({viewport:{width:1440,height:1100}});page.on('pageerror',e=>errors.push(e.message));await page.route(/^https?:/,r=>r.abort());await page.goto(url);let f=page.frames()[1];await f.evaluate(()=>document.fonts.ready);
 const nav=async name=>f.locator(`[data-view=${name}]`).click();await nav('lab');
 ok(await f.locator('.v-section-divider h3').innerText()==='Deck Definition','Latest heading');
 ok((await f.locator('[data-entry=commander]').innerText()).includes('any legal commander, owned or not'),'Unowned commanders explicit');
 ok((await f.locator('.v-input-panel').innerText()).includes('Commander mechanics')&&(await f.locator('.v-input-panel').innerText()).includes('Deck mechanics'),'Two mechanics scopes named');
 ok(await f.locator('.v-run-panel .v-step').count()===0,'Old teaching panel removed');
 const left=await f.locator('.v-input-panel').boundingBox(),right=await f.locator('.v-run-panel').boundingBox();ok(left.width>right.width*1.9&&left.width<right.width*2.1,'Two thirds input, one third progress');
 await f.locator('#v-lab-help').click();ok((await f.locator('#v-dialog').innerText()).includes('Built around your game')&&(await f.locator('#v-dialog').innerText()).toLowerCase().includes('explore → test → decide'),'Help content moved into window');await page.keyboard.press('Escape');
 ok(await f.locator('#v-autobuild').isDisabled(),'Run unavailable before valid input');ok(await f.locator('[data-run-step="0"]').getAttribute('data-phase')==='active','Input step starts blue/active');
 const labels=await f.locator('.v-run-steps strong,.v-run-steps .v-step-link').allTextContents();
 await f.locator('#v-commander-name').fill('Atraxa');await f.locator('#v-find-commander').click();await f.locator('[data-commander-result]').click();ok(!await f.locator('#v-autobuild').isDisabled(),'Selecting legal sample enables Run independent of holdings');
 await f.locator('#v-autobuild').click();ok(await f.locator('[data-run-step="0"]').getAttribute('data-phase')==='complete','Captured input turns green on Run');ok(await f.locator('[data-run-step="1"]').getAttribute('data-phase')==='active','Next step becomes active');ok(await f.locator('#v-budget').isDisabled(),'Run snapshot protected during sequence');
 await f.locator('.v-run-panel').evaluate(e=>e.scrollIntoView({block:'center'}));await page.screenshot({path:qaRoot+'/play-lab-running-1440.png'});
 await f.locator('#v-run-deck:not([disabled])').waitFor({timeout:10000});ok(await f.locator('[data-phase=complete]').count()===6,'Six stages complete');ok(JSON.stringify(labels)===JSON.stringify(await f.locator('.v-run-steps strong,.v-run-steps .v-step-link').allTextContents()),'Step labels never change');ok(!await f.locator('#v-budget').isDisabled(),'Inputs available after completion');
 await f.locator('#v-run-report').click();ok((await f.locator('#v-dialog').innerText()).includes('No simulation results'),'Report never invents measured results');ok((await f.locator('#v-dialog').innerText()).includes('$50'),'Captured budget retained');await page.keyboard.press('Escape');
 await f.locator('#v-run-deck').click();ok((await f.locator('#v-collection-group').inputValue()).startsWith('preview-'),'Completed Deck opens its Collection group');ok((await f.locator('.v-filter-summary').filter({visible:true}).first().innerText()).includes('100 cards'),'Completed list totals 100');ok((await f.locator('#v-roster-counts').innerText()).includes('5owned'),'Preview list creates no owned copies');
 await nav('lab');await f.locator('#v-budget').fill('75');ok(await f.locator('#v-run-report').isDisabled(),'Edited inputs reset current report link');await f.locator('#v-autobuild').click();await f.locator('#v-run-deck:not([disabled])').waitFor({timeout:10000});await f.locator('#v-run-report').click();await f.locator('#v-compare-report').selectOption({index:1});ok((await f.locator('#v-report-comparison').innerText()).includes('$50 → $75'),'Report comparison uses immutable captures');await page.keyboard.press('Escape');
 await page.waitForTimeout(100);ok((await f.locator('#v-report-storage').innerText()).includes('saved in this browser'),'Standalone reports really saved');await page.reload();f=page.frames()[1];await nav('lab');await page.waitForTimeout(250);await f.locator('#v-report-history').click();ok(await f.locator('[data-open-preview]').count()===2,'Report history survives reload');await page.keyboard.press('Escape');
 await f.locator('#v-start').selectOption('list');ok(!await f.locator('#v-autobuild').isDisabled(),'Existing complete list can Run');await f.locator('#v-autobuild').click();await f.locator('#v-run-cancel').click();ok((await f.locator('#v-run-live').innerText()).includes('cancelled'),'Cancel stops sequence');await page.waitForTimeout(1100);ok(await f.locator('#v-run-deck').isDisabled(),'Cancelled run never produces completed deck');
 await nav('collection');await f.locator('[data-filter-toggle]').filter({visible:true}).click();
 for(const id of ['type','subtype','mechanic','color','mv','deck','bench','min','max'])ok(await f.locator(`[data-roster-facet=${id}]`).isVisible(),'Filter present: '+id);
 await f.locator('[data-roster-facet=type]').selectOption('Creature');ok(await f.locator('#v-roster [data-record]').count()===2,'Type filters');await f.locator('[data-roster-facet=subtype]').selectOption('Human');ok((await f.locator('#v-roster tbody').innerText()).includes('Flux Channeler')&&await f.locator('#v-roster [data-record]').count()===1,'Subtype filters');
 await f.locator('[data-clear-filters]').filter({visible:true}).click();await f.locator('#v-roster [data-filter-toggle]').click();await f.locator('[data-roster-facet=mechanic]').selectOption('Proliferate');ok(await f.locator('#v-roster [data-record]').count()===2,'Mechanic filters');await f.locator('[data-roster-facet=color]').selectOption('Blue');ok(await f.locator('#v-roster [data-record]').count()===1,'Color intersects mechanic');
 await f.locator('#v-roster [data-clear-filters]').click();await f.locator('#v-roster [data-filter-toggle]').click();await f.locator('[data-roster-facet=bench]').selectOption('Yes');ok(await f.locator('#v-roster [data-record]').count()===3,'Physical bench includes reserved owned copies');await f.locator('[data-roster-facet=deck]').selectOption('Chulane');ok(await f.locator('#v-roster [data-record]').count()===1,'Deck intersects physical bench');
 await f.locator('#v-roster [data-clear-filters]').click();await f.locator('#v-roster [data-column-toggle]').click();await f.locator('[data-column=source]').uncheck();await f.locator('[data-column=color]').check();ok(await f.locator('#v-roster [data-sort-column=source]').count()===0&&await f.locator('#v-roster [data-sort-column=color]').count()===1,'User replaces Source with Color');
 ok(await f.locator('[data-column=name]').isDisabled(),'Card identifier retained');await f.locator('#v-roster [data-sort=color]').click();ok(await f.locator('#v-roster [data-sort-column=color]').getAttribute('aria-sort')==='ascending','Chosen columns sort');await f.locator('#v-roster [data-table-group]').selectOption('color');ok(await f.locator('#v-roster .v-group-row').count()>1,'New fields group');const cols=await f.locator('#v-roster thead th').count();ok(await f.locator('#v-roster .v-group-row th').first().getAttribute('colspan')===String(cols),'Group spans track column selection');
 const alignment=await f.locator('#v-roster table').evaluate(t=>{const heads=[...t.querySelectorAll('thead th')],cells=[...t.querySelector('tr[data-record]').cells];return heads.every((h,i)=>Math.abs(h.getBoundingClientRect().x-cells[i].getBoundingClientRect().x)<1&&getComputedStyle(cells[i]).textAlign==='left');});ok(alignment,'Headers and values stay aligned left');
 await f.locator('[data-reset-columns]').click();await f.locator('#v-roster [data-table-group]').selectOption('none');await f.locator('#v-roster [data-row-menu=mind] summary').click();await f.locator('#v-roster [data-row-menu=mind] [data-command=offer]').click();await f.locator('#v-roster [data-filter-toggle]').click();await f.locator('#v-roster [data-filter-offer]').check();ok(await f.locator('#v-roster [data-record]').count()===1&&(await f.locator('#v-roster tbody').innerText()).includes('Mind Stone'),'Sell/Trade filtering');
 for(const width of [320,390,736,1024,1440]){await page.setViewportSize({width,height:1000});await nav('lab');await f.locator('#v-start').selectOption('commander');await f.locator('.v-input-panel').evaluate(e=>e.scrollIntoView({block:'start'}));ok(await f.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'Lab fits '+width);if([390,1440].includes(width))await page.screenshot({path:qaRoot+`/play-lab-inputs-${width}.png`});await nav('collection');ok(await f.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'Roster overflow contained '+width);if([390,1440].includes(width))await page.screenshot({path:qaRoot+`/roster-columns-${width}.png`});}
 await nav('lab');await page.emulateMedia({reducedMotion:'reduce'});ok(await f.locator('.v-run-orb i').first().evaluate(e=>getComputedStyle(e).animationName)==='none','Reduced motion respected');
 // Malformed local preview data must not break history or become a trusted report.
 await page.evaluate(()=>{const key='crankmagic.design.preview-reports.v1',reports=JSON.parse(localStorage.getItem(key));reports.push({...reports[0],id:'invalid',intent:{...reports[0].intent,mechanics:'invalid array'}});localStorage.setItem(key,JSON.stringify(reports));});await page.reload();f=page.frames()[1];await nav('lab');await page.waitForTimeout(250);await f.locator('#v-report-history').click();ok(await f.locator('[data-open-preview]').count()===2,'Malformed saved report discarded');await page.keyboard.press('Escape');
 await nav('collection');await f.locator('#v-roster [data-filter-toggle]').click();await f.locator('[data-roster-facet=max]').fill('2');await f.locator('[data-roster-facet=max]').press('Tab');await f.locator('#v-roster [data-column-toggle]').click();await f.locator('[data-column=price]').check();const prices=await f.locator('#v-roster [data-cell=price]').allTextContents();ok(prices.length>0&&prices.every(p=>p.startsWith('$')&&Number(p.slice(1))<=2),'Cost range filters by actual snapshot values');await f.locator('#v-roster [data-clear-filters]').click();
 // The real export keeps its sandbox; its narrow adapter reports quota errors.
 const blocked=await browser.newPage({viewport:{width:1440,height:1000}});blocked.on('pageerror',e=>errors.push(e.message));await blocked.addInitScript(()=>{Storage.prototype.setItem=function(){throw new DOMException('Test quota','QuotaExceededError');};});await blocked.route(/^https?:/,r=>r.abort());await blocked.goto(url);const bf=blocked.frames()[1];await bf.locator('[data-view=lab]').click();await bf.locator('#v-start').selectOption('list');await bf.locator('#v-autobuild').click();await bf.locator('#v-run-deck:not([disabled])').waitFor({timeout:10000});ok((await bf.locator('#v-report-storage').innerText()).includes('Reports stay in this session'),'Storage failure explicitly falls back to session');await bf.locator('#v-report-history').click();ok(await bf.locator('[data-open-preview]').count()===1,'Failed cache write retains session report');await blocked.close();
 ok(errors.length===0,'No runtime errors: '+errors.join('; '));const result={passed:true,checks,offline:true,widths:[320,390,736,1024,1440],errors};writeFileSync(qaRoot+'/run-roster-qa.json',JSON.stringify(result,null,2));console.log(result);
}finally{await browser.close();}
