import assert from 'node:assert/strict';
import {pilotPolicy,PilotPlanningState,DIFFICULTIES} from '../game/contracts/pilot-policy.mjs';
assert.equal(DIFFICULTIES.length,5);
for(const level of [0,6,2.5,'3',null]) assert.throws(()=>pilotPolicy(level));
const planning=new PilotPlanningState([{seatId:1,difficulty:1},{seatId:2,difficulty:5},{seatId:3,difficulty:3}]);
const decision={seatId:1,decisionId:'draw-followup',stateVersion:18,options:[{optionId:'hold'},{optionId:'cast:7'}]};
const ticket=planning.beginDecision(decision),reply={decisionId:decision.decisionId,stateVersion:18,optionId:'hold'};
assert.equal(planning.accepts(ticket,reply,18),true);
planning.invalidate([1],'card-drawn');
assert.equal(planning.accepts(ticket,reply,18),false,'A card draw invalidates an in-flight evaluation even before the next action');
planning.invalidate([1],'card-drawn');
const next=planning.beginDecision({...decision,stateVersion:19});
assert.equal(next.generation,ticket.generation+2,'Two draws create two invalidations');
assert.equal(planning.accepts(next,{...reply,stateVersion:19,optionId:'invented'},19),false);
assert.equal(planning.accepts(next,{...reply,stateVersion:19},20),false);
assert.equal(planning.beginDecision({...decision,seatId:2}).policy.level,5,'Difficulty is independent at each seat');
assert.equal(planning.beginDecision({...decision,seatId:3}).policy.observation,ticket.policy.observation,'Difficulty never grants hidden information');
assert.throws(()=>planning.beginDecision({...decision,options:[]}));
console.log('Commander pilots: per-seat difficulty, per-draw invalidation, stale/illegal answers, identical information boundary passed');
