import {PLAYMATS,defaultPlaymat,validPlaymat,readMatPreferences,saveMatPreference} from '/playmats.mjs';
let catalog,config,prepared,activeLobby,busy=false,lobbyTimer,aiApiKey='';const inviteEmails=new Map();
const hostRematchDraft={source:'library',name:'',deckId:'',commander:'',archidektUrl:'',csv:''};
const e=(tag,cls,text)=>{const n=document.createElement(tag);if(cls)n.className=cls;if(text!==undefined)n.textContent=text;return n;};
const button=(text,fn,cls='')=>{const n=e('button',cls,text);n.type='button';n.addEventListener('click',fn);return n;};
const money=n=>`$${Number(n).toFixed(2)}`;
const dialog=e('dialog','game-setup');dialog.id='game-setup';dialog.setAttribute('aria-label','Game setup');document.body.append(dialog);
const head=e('div','setup-heading');head.append(e('div','', 'GAME SETUP · COMMANDER'));
function exitSetup(){if(window.parent===window)location.href='/app/#decks';else window.parent.postMessage({type:'crankmagic-exit'},location.origin);}
const close=e('button','','Close setup ×');close.addEventListener('click',()=>{if(document.body.classList.contains('setup-screen'))exitSetup();else dialog.close();});head.append(close);dialog.append(head);
dialog.addEventListener('cancel',event=>{if(document.body.classList.contains('setup-screen')){event.preventDefault();exitSetup();}});
const actions=e('div','setup-actions');head.append(actions);
const content=e('div','setup-content');dialog.append(content);
function select(label,value,options,onChange){const box=e('label','setup-field');box.append(e('span','',label));const s=e('select');s.setAttribute('aria-label',label);for(const [id,text,disabled]of options){const o=e('option','',text);o.value=id;o.disabled=!!disabled;s.append(o);}s.value=value;s.addEventListener('change',()=>onChange(s.value));box.append(s);return box;}
function input(label,value,type,onChange){const box=e('label','setup-field');box.append(e('span','',label));const field=e('input');field.type=type;field.value=value;field.setAttribute('aria-label',label);if(type==='number'){field.min=1;field.max=10000;}field.addEventListener('input',()=>onChange(type==='number'?Number(field.value):field.value));box.append(field);return box;}
function matPicker(s){
  const selected=s.playmat||defaultPlaymat(s.seatId),picker=e('details','mat-picker');
  picker.append(e('summary','', 'Playmat · '+(selected==='random'?'Random':PLAYMATS.find(m=>m.id===selected)?.name||'Runic cube')));
  const grid=e('fieldset','mat-choices');grid.append(e('legend','',s.seatId?'Choose this AI player’s playmat':'Choose your playmat'));
  for(const mat of [{id:'random',name:'Random',image:null},...PLAYMATS]){
    const label=e('label','mat-choice'),radio=e('input');radio.type='radio';radio.name='playmat-'+s.seatId;radio.value=mat.id;radio.checked=mat.id===selected;radio.setAttribute('aria-label',(s.seatId?'AI '+s.seatId:'Your')+' playmat: '+mat.name);
    if(mat.image){const img=e('img');img.src=mat.image;img.alt='';img.loading='lazy';label.append(img);}else label.append(e('span','mat-swatch',mat.id==='random'?'⚄':'✦'));
    radio.addEventListener('change',()=>{s.playmat=mat.id;saveMatPreference(s.seatId,mat.id);prepared=null;try{localStorage.setItem('commander-setup-v1',JSON.stringify(config));}catch{}picker.querySelector('summary').textContent='Playmat · '+mat.name;content.querySelector('.setup-result').replaceChildren();actions.querySelector('.setup-start').disabled=true;});
    label.append(radio,e('span','',mat.name));grid.append(label);
  }
  picker.append(grid);return picker;
}
function invalidate(redraw=true){prepared=null;try{localStorage.setItem('commander-setup-v1',JSON.stringify(config));}catch{}if(redraw)render();else{content.querySelector('.setup-result')?.replaceChildren();const start=actions.querySelector('.setup-start');if(start)start.disabled=true;}}
function reshapeSeats(humans,ais){
  const oldHumans=config.humans,old=config.seats,host={...old[0],seatId:0,kind:'human'},humanPool=old.slice(1,oldHumans).filter(s=>s.kind!=='ai'),aiPool=old.slice(oldHumans).filter(s=>s.kind==='ai'||oldHumans===1);
  config.humans=humans;config.ais=ais;config.seats=[host];
  for(let i=1;i<humans;i++)config.seats.push({...humanPool[i-1],seatId:i,kind:'human',name:humanPool[i-1]?.name||`Friend ${i}`,source:humanPool[i-1]?.source||'preloaded',commanderMode:'selected',commander:humanPool[i-1]?.commander||'',deckId:humanPool[i-1]?.deckId||''});
  for(let i=0;i<ais;i++){const fallback=catalog.defaults.seats[i+1]||catalog.defaults.seats[1],seat=aiPool[i]||fallback;config.seats.push({...structuredClone(seat),seatId:humans+i,kind:'ai'});}
  invalidate();
}
function setSource(s,value){s.source=value;s.archidektUrl='';s.deckId='';const first=catalog.decks.find(d=>d.source===value&&d.commander===s.commander&&d.cost<=config.maxCost)||catalog.decks.find(d=>d.source===value&&d.ok&&d.cost<=config.maxCost);if(first){s.deckId=first.id;s.commander=first.commander;}invalidate();}
async function post(path,body){const response=await fetch(path,{method:'POST',headers:{'Content-Type':'application/json','X-Commander-Token':catalog.token},body:JSON.stringify(body)});const value=await response.json();if(!response.ok)throw Error(value.error||'Request failed');return value;}
function hostDeckPanel(){
  const panel=e('section','setup-seat host-rematch-deck');panel.append(e('h2','','Choose your deck for the next game'),e('p','setup-note','Keep the current hundred, choose another saved list, upload a Moxfield export, or build from a commander. Your friends choose independently in their browsers.'));
  const fields=e('div','setup-fields'),source=e('select');source.setAttribute('aria-label','Your next deck source');for(const [id,label]of [['library','Your saved CrankMagic decks'],['preloaded','Preloaded variations'],['upload','Upload Moxfield two-column CSV'],['lab','Build with Deck Lab'],['archidekt','Load an Archidekt deck']]){const o=e('option','',label);o.value=id;source.append(o);}source.value=hostRematchDraft.source;
  const name=e('input');name.placeholder='Player or deck name';name.setAttribute('aria-label','Your player or deck name');name.value=hostRematchDraft.name||config.seats[0].name||'';name.oninput=()=>hostRematchDraft.name=name.value;
  const saved=e('select');saved.setAttribute('aria-label','Your saved deck');const commander=e('select');commander.setAttribute('aria-label','Commander for Deck Lab or Archidekt');for(const value of catalog.commanders.map(c=>c.name)){const o=e('option','',value);o.value=value;commander.append(o);}commander.value=hostRematchDraft.commander||config.seats[0].commander||commander.value;commander.onchange=()=>hostRematchDraft.commander=commander.value;
  const url=e('input');url.type='url';url.placeholder='Optional Archidekt deck URL';url.setAttribute('aria-label','Archidekt deck URL');url.value=hostRematchDraft.archidektUrl;url.oninput=()=>hostRematchDraft.archidektUrl=url.value;
  const file=e('input');file.type='file';file.accept='.csv,text/csv';file.setAttribute('aria-label','Moxfield deck CSV');const csv=e('textarea');csv.placeholder='Card Name,Count\nForest,99\n\nCommander Name,1';csv.setAttribute('aria-label','Moxfield CSV contents');csv.value=hostRematchDraft.csv;csv.oninput=()=>hostRematchDraft.csv=csv.value;file.onchange=async()=>{csv.value=file.files[0]?await file.files[0].text():'';hostRematchDraft.csv=csv.value;};
  const refreshSaved=()=>{saved.replaceChildren();for(const d of catalog.decks.filter(d=>d.source===source.value&&d.ok)){const o=e('option','',`${d.name} · ${d.commander} · ${money(d.cost)}`);o.value=d.id;o.dataset.commander=d.commander;saved.append(o);}if(hostRematchDraft.deckId&&[...saved.options].some(o=>o.value===hostRematchDraft.deckId))saved.value=hostRematchDraft.deckId;};
  const update=()=>{hostRematchDraft.source=source.value;refreshSaved();saved.hidden=!['library','preloaded'].includes(source.value);commander.hidden=!['lab','archidekt'].includes(source.value);url.hidden=source.value!=='archidekt';file.hidden=csv.hidden=source.value!=='upload';};source.onchange=update;saved.onchange=()=>{hostRematchDraft.deckId=saved.value;hostRematchDraft.commander=saved.selectedOptions[0]?.dataset.commander||'';};update();
  const use=button('Validate and use this deck',async()=>{try{use.disabled=true;let body={source:source.value,name:name.value};if(source.value==='upload')body.csv=csv.value;else if(['library','preloaded'].includes(source.value)){body.deckId=saved.value;body.commander=saved.selectedOptions[0]?.dataset.commander;}else{body.commander=commander.value;if(source.value==='archidekt')body.archidektUrl=url.value;}const value=await post('/api/lobby-deck',body);activeLobby={...activeLobby,...value};renderLobby('Your next deck is validated. Press Ready when you are finished choosing.');}catch(error){renderLobby(error.message);}finally{use.disabled=false;}},'setup-start');
  fields.append(source,name,saved,commander,url,file,csv,use);panel.append(fields);return panel;
}
function renderLobby(message=''){
  const table=activeLobby.table;content.replaceChildren();actions.replaceChildren();const lead=e('div','setup-intro');lead.append(e('h1','','Your live table'),e('p','',`Bracket ${table.settings.bracket} · $${table.settings.maxCost} maximum per deck · ${table.seats.length} players`));content.append(lead);
  if(message)content.append(e('p','setup-message',message));
  if(/^http:\/\/(?:127\.0\.0\.1|localhost)/.test(activeLobby.guestOrigin))content.append(e('p','setup-note','These invitation links currently reach this computer only. Configure the documented HTTPS guest origin before inviting a friend on another device. The private admin service remains local.'));
  const seats=e('div','lobby-seats');for(const seat of table.seats){const card=e('section',`lobby-seat setup-seat-${seat.seatId}`);card.append(e('h2','',seat.seatId===0?'You · host':seat.name||`Seat ${seat.seatId+1}`),e('p','',seat.kind==='ai'?'AI player':seat.seatId===0?'Human player':seat.occupied?'Invitation claimed':'Waiting for invited player'),e('strong','lobby-state',seat.ready?'Ready':seat.connected?'Choosing a deck':'Not connected'));if(seat.commander)card.append(e('small','',seat.commander));
    const invite=activeLobby.invitations?.find(i=>i.seatId===seat.seatId),newInvite=async()=>{try{const value=await post('/api/lobby-invite',{seatId:seat.seatId});activeLobby.invitations=activeLobby.invitations.filter(i=>i.seatId!==seat.seatId);activeLobby.invitations.push(value);renderLobby(invite?'The previous unclaimed invitation was replaced.':'A private invitation is ready.');}catch(error){renderLobby(error.message);}};if(seat.kind==='human'&&seat.seatId>0&&!seat.occupied){if(invite){const qr=e('div','invite-qr');if(globalThis.CrankQR)qr.innerHTML=globalThis.CrankQR.svg(invite.link,{label:`Join ${seat.name||'Commander table'}`});const link=e('input');link.value=invite.link;link.readOnly=true;link.setAttribute('aria-label',`Invitation link for ${seat.name||'seat '+(seat.seatId+1)}`);const email=e('input');email.type='email';email.placeholder='friend@example.com';email.value=inviteEmails.get(seat.seatId)||'';email.setAttribute('aria-label',`Email address for ${seat.name||'seat '+(seat.seatId+1)}`);email.addEventListener('input',()=>inviteEmails.set(seat.seatId,email.value));const remote=/^https:\/\//.test(activeLobby.guestOrigin),send=button('Email invitation',()=>{if(!email.reportValidity())return;const subject='Your CrankMagic Online Commander seat',expires=Math.max(1,Math.round(invite.expiresIn/3_600_000)),body=`You have a reserved seat at ${seat.name||'our Commander table'}.\n\nOpen this private link in your browser to claim your seat, choose your deck, and mark yourself ready:\n${invite.link}\n\nNo installation or Cloudflare account is required. This single-use link expires in about ${expires} hours. Do not forward it.\n\nCrankMagic Online`;location.href=`mailto:${encodeURIComponent(email.value)}?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`;},'email-invite');send.disabled=!remote;send.title=remote?'Open this invitation in your default email app.':'Restart CrankMagic with -RemoteGuests before emailing an invitation.';card.append(qr,link,email,button('Copy invitation',async()=>{await navigator.clipboard.writeText(invite.link);link.select();},'copy-invite'),send,button('Create a new invitation',newInvite));}else card.append(button('Create invitation',newInvite,'setup-start'));}
    seats.append(card);}content.append(seats);
  const hostSeat=table.seats[0];if(table.phase==='selecting'&&table.generation>0)content.append(hostDeckPanel());if(table.phase==='selecting'||table.phase==='countdown'){const ready=button(hostSeat.ready?'Mark me not ready':'Ready with this deck',async()=>{try{await post('/api/lobby-ready',{ready:!hostSeat.ready});await refreshLobby();}catch(error){renderLobby(error.message);}},hostSeat.ready?'':'setup-start');ready.disabled=!hostSeat.deckVersion;actions.append(ready);}
  if(table.phase==='countdown')actions.append(e('strong','countdown',`Starting in ${Math.max(0,Math.ceil((table.countdownAt-Date.now())/1000))}`));
  if(table.phase==='playing')actions.append(button('Return to game',()=>window.dispatchEvent(new Event('crankmagic-game-ready')),'setup-start'));
  if(table.phase==='rematch'){if(hostSeat.rematch===true)actions.append(e('strong','waiting','Waiting for the other players…'));else actions.append(button('Yes, play another game',async()=>{await post('/api/lobby-rematch',{accept:true});await refreshLobby();},'setup-start'),button('No',async()=>{await post('/api/lobby-rematch',{accept:false});await refreshLobby();}));}
  if(['selecting','rematch'].includes(table.phase))actions.append(button('Close table',async()=>{try{await post('/api/lobby-close',{});clearTimeout(lobbyTimer);activeLobby=null;render('The multiplayer table is closed.');}catch(error){renderLobby(error.message);}}));
}
async function refreshLobby(){
  clearTimeout(lobbyTimer);if(!activeLobby)return;try{const response=await fetch('/api/table',{headers:{'X-Commander-Token':catalog.token}}),value=await response.json();if(!response.ok)throw Error(value.error);activeLobby=value;renderLobby();if(value.table.phase==='playing')window.dispatchEvent(new Event('crankmagic-game-ready'));else lobbyTimer=setTimeout(refreshLobby,1000);}catch(error){renderLobby(error.message);lobbyTimer=setTimeout(refreshLobby,3000);}
}
function render(message=''){
  if(activeLobby){renderLobby(message);return;}
  content.replaceChildren();const lead=e('div','setup-intro');lead.append(e('h1','','Build your table'),e('p','',`You choose the opponents, their commanders, and where each hundred comes from. ${catalog.variantCount} archived variations · ${catalog.rungCount} complete Base / Tuned / Fun / Max lists available.`));content.append(lead);
  const global=e('div','setup-globals');
  global.append(select('Table bracket',config.bracket,[[1,'1 · Exhibition'],[2,'2 · Core'],[3,'3 · Upgraded'],[4,'4 · Optimized'],[5,'5 · cEDH']],v=>{config.bracket=+v;invalidate();}),input('Maximum deck cost · USD · every player',config.maxCost,'number',v=>{config.maxCost=v;invalidate(false);}),select('Human players',config.humans,[1,2,3,4].map(n=>[n,n===1?'1 · You':`${n} · You + ${n-1} friend${n>2?'s':''}`,n+config.ais>4||n+config.ais<2]),v=>reshapeSeats(+v,config.ais)),select('AI players',config.ais,[0,1,2,3].map(n=>[n,`${n} AI${n===1?'':' players'}`,n+config.humans>4||n+config.humans<2]),v=>reshapeSeats(config.humans,+v)));content.append(global);
  config.aiProvider??=(catalog.aiCredential?.openaiAvailable?'openai':'native');config.aiModel??='gpt-5.6-luna';
  global.append(select('AI controller',config.aiProvider,[['native','Forge native AI · no API cost'],['openai','OpenAI API pilot'],['anthropic','Anthropic API pilot']],v=>{config.aiProvider=v;config.aiModel=v==='anthropic'?'claude-haiku-4-5-20251001':'gpt-5.6-luna';invalidate();}));
  if(config.aiProvider!=='native'){
    const models=config.aiProvider==='openai'?[['gpt-5.6-luna','GPT-5.6 Luna · default'],['gpt-5.6-terra','GPT-5.6 Terra · stronger fallback']]:[['claude-haiku-4-5-20251001','Claude Haiku 4.5']];global.append(select('AI model',config.aiModel,models,v=>{config.aiModel=v;invalidate(false);}));
    if(config.aiProvider==='openai'&&catalog.aiCredential?.openaiAvailable)global.append(e('p','setup-note','Windows Credential Manager is connected. The OpenAI key stays on this computer and is loaded only into the local host process.'));
    else{const key=input('AI API key · held in local memory only',aiApiKey,'password',v=>{aiApiKey=v;});key.querySelector('input').autocomplete='new-password';global.append(key,e('p','setup-note','The key is sent only to the loopback host, held in process memory, excluded from game files and logs, and cleared when that host stops. Provider calls use only the AI seat’s permitted view and Forge-offered actions.'));}
  }
  content.append(e('p','setup-note',`Budget includes all 100 cards and the commander, using recorded USD estimates dated ${catalog.priceAsOf.slice(0,10)}; missing prices block preparation. Bracket checks include known Game Changers; play-pattern restrictions still require a table agreement. Bracket and AI difficulty are different settings.`));
  const seats=e('div','setup-seats');let aiOrdinal=0;
  for(const s of config.seats){
    const ai=s.kind==='ai',guest=s.kind==='human'&&s.seatId>0,aiNumber=ai?++aiOrdinal:null;
    const card=e('section',`setup-seat setup-seat-${s.seatId}`),title=e('div','setup-seat-title');title.append(e('h2','',ai?`AI player ${aiNumber}`:guest?`Invited human · seat ${s.seatId+1}`:'You · host'));card.append(title);
    const seatLabel=ai?`AI ${aiNumber}`:guest?'Friend':'Your';
    const fields=e('div','setup-fields');fields.append(input(`${seatLabel} name`,s.name,'text',v=>{s.name=v;invalidate(false);}));
    if(guest){fields.append(e('p','setup-note','This player chooses their commander and deck after opening the private invitation. The host never receives their hand or private choices.'));card.append(fields);seats.append(card);continue;}
    fields.append(select(`${seatLabel} deck source`,s.source,[['library','Your saved decks'],['preloaded','Preloaded variations · 200 lists'],['lab','Deck Lab · build a starting list'],['archidekt','Archidekt · find a matching deck']],v=>setSource(s,v)));
    const savedSource=['library','preloaded'].includes(s.source);
    const commanders=savedSource?[...new Set(catalog.decks.filter(d=>d.source===s.source).map(d=>d.commander))].sort():catalog.commanders.map(c=>c.name);
    if(ai||!savedSource)fields.append(select(`${seatLabel} commander`,s.commanderMode==='random'?'__random__':s.commander,[...(ai?[['__random__','Random commander']]:[]),...commanders.map(n=>[n,n])],v=>{s.commanderMode=v==='__random__'?'random':'selected';if(s.commanderMode==='selected')s.commander=v;s.deckId='';invalidate();}));
    if(s.commanderMode==='selected'&&savedSource){
      const available=catalog.decks.filter(d=>d.source===s.source&&(!ai||d.commander===s.commander));
      fields.append(select(`${seatLabel} deck list`,s.deckId||'',[['',ai?'Choose a matching list for me':'Select your deck',!ai],...available.map(d=>[d.id,`${d.name} · ${money(d.cost)}${d.ok?'':' · needs validation'}`])],v=>{s.deckId=v;const selected=available.find(d=>d.id===v);if(selected)s.commander=selected.commander;invalidate();}));
      if(!ai)fields.append(e('p','setup-note',`Commander: ${s.commander}. Your deck supplies its commander.`));
    }else if(s.commanderMode==='random')fields.append(e('p','setup-note','Random choices are drawn from the selected source. Saved lists are filtered by bracket and budget first; the resolved commander is shown before launch.'));
    if(s.source==='lab')fields.append(e('p','setup-note','Uses the existing Lab draft builder and your catalog. This produces a starting hundred; simulation optimization is not connected yet.'));
    if(s.source==='archidekt')fields.append(input(`${seatLabel} Archidekt URL · optional`,s.archidektUrl||'','url',v=>{s.archidektUrl=v;invalidate(false);}),e('p','setup-note','Search checks up to 12 public candidates, then verifies commander, quantity, known identities, bracket counts, and budget. No match is reported explicitly; sources are never silently substituted.'));
    if(ai){fields.append(select(`AI ${aiNumber} play style`,s.nativeProfile,[['Default','Balanced · Forge Default'],['Cautious','Cautious · Forge profile'],['Reckless','Reckless · Forge profile']],v=>{s.nativeProfile=v;invalidate();}),select(`AI ${aiNumber} difficulty`,s.difficulty,[[1,'1 · Learner'],[2,'2 · Casual'],[3,'3 · Focused'],[4,'4 · Advanced'],[5,'5 · Expert']],v=>{s.difficulty=+v;invalidate();}));}
    card.append(fields,matPicker(s));seats.append(card);
  }
  content.append(seats,e('p','setup-note',config.humans>1?'Opening the lobby creates one private, single-use invitation for each human seat. Each friend validates their own deck and presses Ready; the game starts after a shared 5-second countdown.':config.aiProvider==='native'?'This local table uses browser controls backed by Forge. Play style selects a Forge native-AI profile.':'API AI seats use the same browser decision bridge as a human, receive only their own private view, and can act through Forge-implemented card rules even when Forge marks a card as unsuitable for its native AI deck builder.'));
  const result=e('div','setup-result');result.setAttribute('aria-live','polite');if(message)result.append(e('p','setup-message',message));
  if(prepared){result.append(e('h2','','Your prepared pod'));for(const seat of prepared.pod.seats){const row=e('div','prepared-seat'),art=seat.deck.commanders[0].art.normal;if(art){const img=e('img');img.src=art;img.alt=seat.deck.commanders[0].name;row.append(img);}row.append(e('div','',`${seat.name} · ${seat.deck.commanders.map(c=>c.name).join(' + ')}\n${seat.deck.name}\n${seat.check.total} cards · ${money(seat.check.cost)} · ${seat.check.gameChangers} Game Changers\n${seat.kind==='ai'?(seat.pilot.kind==='api'?`API AI · difficulty ${seat.pilot.difficultyRequested}`:`Native AI · ${seat.nativeProfile}`):'Human'} · ${seat.source}`));result.append(row);}result.append(e('p','setup-note',prepared.pod.seats.some(s=>s.pilot?.kind==='api')?'Forge still owns all rules, costs and legal actions. The model chooses only from the API seat’s current offered browser actions; provider failures and fallbacks are recorded without storing provider responses or the key.':'Forge performs the final Commander legality check before opening the match. Native AI remains an uncertified gameplay driver.'));}
  content.append(result);actions.replaceChildren();
  if(prepared)for(const seat of prepared.pod.seats.filter(s=>s.kind==='ai'&&s.pilot?.kind!=='api'&&s.aiCompatibility?.warnings.length)){const warning=e('p','compatibility-note',`${seat.name} · Native AI limitations: ${seat.aiCompatibility.warnings.join(', ')}. These cards stay in the deck; Forge flags its own AI decision support. Its normal casting and activation choices exclude these flagged cards. Card rules and mandatory triggers can still work. Select an API pilot to use the browser-visible actions for these Forge-implemented cards.`);result.append(warning);}
  const prepare=e('button','',busy?'Working…':'Prepare decks');prepare.disabled=busy||(['library','preloaded'].includes(config.seats[0].source)&&!config.seats[0].deckId);prepare.addEventListener('click',async()=>{busy=true;render('Resolving decks and checking this table…');try{if(config.aiProvider!=='native'){if(aiApiKey||config.aiProvider==='openai'&&catalog.aiCredential?.openaiAvailable){await post('/api/ai-session',{provider:config.aiProvider,model:config.aiModel,key:aiApiKey,useStoredCredential:!aiApiKey&&config.aiProvider==='openai'});aiApiKey='';}const aiSeats=config.seats.map(s=>s.kind==='ai'?{...s,aiProvider:config.aiProvider,aiModel:config.aiModel}:s);prepared=await post('/api/prepare',{...config,seats:aiSeats});}else prepared=await post('/api/prepare',{...config,seats:config.seats.map(s=>s.kind==='ai'?{...s,aiProvider:null,aiModel:null}:s)});busy=false;render('Decks prepared. Review the resolved commanders and costs below.');content.querySelector('.setup-result').scrollIntoView({block:'start'});}catch(error){busy=false;prepared=null;render(error.message);}});
  const start=e('button','setup-start',config.humans>1?'Open lobby':'Launch game');start.disabled=busy||!prepared;start.addEventListener('click',async()=>{busy=true;render(config.humans>1?'Creating private invitations…':'Starting the local rules engine and CrankMagic Online…');try{const value=await post('/api/start',{id:prepared.id});prepared=null;if(value.lobby){busy=false;activeLobby=value;renderLobby();refreshLobby();}else pollStatus();}catch(error){busy=false;render(error.message);}});
  actions.append(prepare,start);
  if(busy)for(const field of content.querySelectorAll('input,select'))field.disabled=true;
}
async function pollStatus(){try{const s=await fetch('/api/live').then(r=>r.json());if(s.status==='starting'){render('Forge is loading the card database and game window…');setTimeout(pollStatus,2000);}else{busy=false;if(['ready','playing'].includes(s.status))window.dispatchEvent(new Event('crankmagic-game-ready'));render(['ready','playing'].includes(s.status)?'Your live browser table is ready. Complex prompts may require the engine window.':`Game status: ${s.status}${s.error?` · ${s.error}`:''}`);}}catch(error){busy=false;render(error.message);}}
export async function openGameSetup(imported){
  if(!imported){const transfer=sessionStorage.getItem('crankmagic-imported-deck');if(transfer){sessionStorage.removeItem('crankmagic-imported-deck');try{const saved=JSON.parse(transfer);if(saved.expires>Date.now())imported=saved.deck;}catch{/* An invalid or expired transfer leaves the previous setup intact. */}}}
  if(!catalog){catalog=await fetch('/api/setup').then(r=>{if(!r.ok)throw Error('Restart the local server to load Game Setup');return r.json();});config=structuredClone(catalog.defaults);try{const saved=JSON.parse(localStorage.getItem('commander-setup-v1'));if(saved?.seats?.length===saved?.humans+saved?.ais&&saved.humans>=1&&saved.humans<=4&&saved.ais>=0&&saved.ais<=3&&saved.humans+saved.ais>=2&&saved.humans+saved.ais<=4)config=saved;}catch{}config.seats=config.seats.map((s,i)=>({...s,seatId:i,kind:i<config.humans?'human':'ai'}));config.aiProvider??=(catalog.aiCredential?.openaiAvailable?'openai':'native');config.aiModel=['gpt-5.6-luna','gpt-5.6-terra','claude-haiku-4-5-20251001'].includes(config.aiModel)?config.aiModel:'gpt-5.6-luna';if(catalog.aiCredential?.openaiAvailable&&!localStorage.getItem('commander-openai-credential-default-v1')){config.aiProvider='openai';config.aiModel='gpt-5.6-luna';localStorage.setItem('commander-openai-credential-default-v1','applied');}}
  Object.assign(hostRematchDraft,{source:config.seats[0].source||'library',name:config.seats[0].name||'',deckId:config.seats[0].deckId||'',commander:config.seats[0].commander||''});
  if(imported){catalog=await fetch('/api/setup').then(r=>r.json());Object.assign(config.seats[0],{source:'library',deckId:imported.id,commander:imported.commander,commanderMode:'selected'});prepared=null;}
  if(!activeLobby)try{const response=await fetch('/api/table',{headers:{'X-Commander-Token':catalog.token}});if(response.ok)activeLobby=await response.json();}catch{/* No open multiplayer table leaves the normal setup visible. */}
  const matPreferences=readMatPreferences();for(const s of config.seats)s.playmat=validPlaymat(matPreferences[s.seatId])?matPreferences[s.seatId]:validPlaymat(s.playmat)?s.playmat:defaultPlaymat(s.seatId);
  const current=await fetch('/api/live').then(r=>r.json());
  head.querySelector('.setup-resume')?.remove();
  head.querySelector('.setup-end')?.remove();
  render(imported?'Your current CrankMagic deck has been received. Prepare the table to check costs and mechanics.':'');if(activeLobby)refreshLobby();if(['ready','playing'].includes(current.status)){const resume=e('button','setup-resume','Resume current table');resume.addEventListener('click',()=>window.dispatchEvent(new Event('crankmagic-game-ready')));head.insertBefore(resume,close);}
  if(['ready','playing','finished'].includes(current.status)&&!current.resumed){const end=e('button','setup-end','End current game');end.addEventListener('click',async()=>{if(end.dataset.confirm!=='yes'){end.dataset.confirm='yes';end.textContent='End game · keep journal';render('Ending this game keeps its local journal, but the live position cannot be resumed. Click End game again to return to a fresh setup.');return;}try{end.disabled=true;await post('/api/close-game',{});window.dispatchEvent(new Event('crankmagic-game-closed'));await openGameSetup();}catch(error){end.disabled=false;render(error.message);}});head.insertBefore(end,close);}
  document.body.classList.add('setup-screen');if(window.parent!==window)window.parent.postMessage({type:'crankmagic-mode',mode:'setup'},location.origin);
  if(!dialog.open)dialog.show();
}
